// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the AirlineLeg schema. See the pinned OpenAPI specification.
 */
public class AirlineLeg extends JsonModel {
	public AirlineLeg() {
		super();
	}

	public AirlineLeg(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code departure_airport}; required. Absent values return null.
	 */
	public String getDepartureAirport() {
		return read("departure_airport", String.class);
	}

	/**
	 * Sets {@code departure_airport}; null removes the field.
	 */
	public AirlineLeg setDepartureAirport(String value) {
		put("departure_airport", value);
		return this;
	}

	/**
	 * API field {@code destination_airport}; required. Absent values return null.
	 */
	public String getDestinationAirport() {
		return read("destination_airport", String.class);
	}

	/**
	 * Sets {@code destination_airport}; null removes the field.
	 */
	public AirlineLeg setDestinationAirport(String value) {
		put("destination_airport", value);
		return this;
	}

	/**
	 * API field {@code departure_date}; required. Absent values return null.
	 */
	public String getDepartureDate() {
		return read("departure_date", String.class);
	}

	/**
	 * Sets {@code departure_date}; null removes the field.
	 */
	public AirlineLeg setDepartureDate(String value) {
		put("departure_date", value);
		return this;
	}

	/**
	 * Parsed {@code departure_date}.
	 */
	public java.time.LocalDate getDepartureDateAsDate() {
		return readDate("departure_date");
	}

	/**
	 * Sets {@code departure_date} as an ISO-8601 date; null removes the field.
	 */
	public AirlineLeg setDepartureDateAsDate(java.time.LocalDate value) {
		putDate("departure_date", value);
		return this;
	}

	/**
	 * API field {@code carrier_code}; optional. Absent values return null.
	 */
	public String getCarrierCode() {
		return read("carrier_code", String.class);
	}

	/**
	 * Sets {@code carrier_code}; null removes the field.
	 */
	public AirlineLeg setCarrierCode(String value) {
		put("carrier_code", value);
		return this;
	}
}
