// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Airline schema. See the pinned OpenAPI specification.
 */
public class Airline extends JsonModel {
	public Airline() {
		super();
	}

	public Airline(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code ticket_number}; optional. Absent values return null.
	 */
	public String getTicketNumber() {
		return read("ticket_number", String.class);
	}

	/**
	 * Sets {@code ticket_number}; null removes the field.
	 */
	public Airline setTicketNumber(String value) {
		put("ticket_number", value);
		return this;
	}

	/**
	 * API field {@code booking_reference}; optional. Absent values return null.
	 */
	public String getBookingReference() {
		return read("booking_reference", String.class);
	}

	/**
	 * Sets {@code booking_reference}; null removes the field.
	 */
	public Airline setBookingReference(String value) {
		put("booking_reference", value);
		return this;
	}

	/**
	 * API field {@code passengers}; optional. Absent values return null.
	 */
	public java.util.List<AirlinePassenger> getPassengers() {
		return read("passengers", new com.google.gson.reflect.TypeToken<java.util.List<AirlinePassenger>>() {
		}.getType());
	}

	/**
	 * Sets {@code passengers}; null removes the field.
	 */
	public Airline setPassengers(java.util.List<AirlinePassenger> value) {
		put("passengers", value);
		return this;
	}

	/**
	 * API field {@code legs}; optional. Absent values return null.
	 */
	public java.util.List<AirlineLeg> getLegs() {
		return read("legs", new com.google.gson.reflect.TypeToken<java.util.List<AirlineLeg>>() {
		}.getType());
	}

	/**
	 * Sets {@code legs}; null removes the field.
	 */
	public Airline setLegs(java.util.List<AirlineLeg> value) {
		put("legs", value);
		return this;
	}
}
