// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the AirlinePassenger schema. See the pinned OpenAPI specification.
 */
public class AirlinePassenger extends JsonModel {
	public AirlinePassenger() {
		super();
	}

	public AirlinePassenger(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code first_name}; required. Absent values return null.
	 */
	public String getFirstName() {
		return read("first_name", String.class);
	}

	/**
	 * Sets {@code first_name}; null removes the field.
	 */
	public AirlinePassenger setFirstName(String value) {
		put("first_name", value);
		return this;
	}

	/**
	 * API field {@code last_name}; required. Absent values return null.
	 */
	public String getLastName() {
		return read("last_name", String.class);
	}

	/**
	 * Sets {@code last_name}; null removes the field.
	 */
	public AirlinePassenger setLastName(String value) {
		put("last_name", value);
		return this;
	}
}
