// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the AuthorizationDetails schema. See the pinned OpenAPI specification.
 */
public class AuthorizationDetails extends JsonModel {
	public AuthorizationDetails() {
		super();
	}

	public AuthorizationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code rrn}; optional. Absent values return null.
	 */
	public String getRrn() {
		return read("rrn", String.class);
	}

	/**
	 * Sets {@code rrn}; null removes the field.
	 */
	public AuthorizationDetails setRrn(String value) {
		put("rrn", value);
		return this;
	}

	/**
	 * API field {@code auth_code}; optional. Absent values return null.
	 */
	public String getAuthCode() {
		return read("auth_code", String.class);
	}

	/**
	 * Sets {@code auth_code}; null removes the field.
	 */
	public AuthorizationDetails setAuthCode(String value) {
		put("auth_code", value);
		return this;
	}

	/**
	 * API field {@code three_d_secure}; required. Absent values return null.
	 */
	public ThreeDSecureDetails getThreeDSecure() {
		return read("three_d_secure", ThreeDSecureDetails.class);
	}

	/**
	 * Sets {@code three_d_secure}; null removes the field.
	 */
	public AuthorizationDetails setThreeDSecure(ThreeDSecureDetails value) {
		put("three_d_secure", value);
		return this;
	}
}
