// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the B2bSberbankPayerBankDetails schema. See the pinned OpenAPI specification.
 */
public class B2bSberbankPayerBankDetails extends JsonModel {
	public B2bSberbankPayerBankDetails() {
		super();
	}

	public B2bSberbankPayerBankDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code full_name}; required. Absent values return null.
	 */
	public String getFullName() {
		return read("full_name", String.class);
	}

	/**
	 * Sets {@code full_name}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setFullName(String value) {
		put("full_name", value);
		return this;
	}

	/**
	 * API field {@code short_name}; required. Absent values return null.
	 */
	public String getShortName() {
		return read("short_name", String.class);
	}

	/**
	 * Sets {@code short_name}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setShortName(String value) {
		put("short_name", value);
		return this;
	}

	/**
	 * API field {@code address}; required. Absent values return null.
	 */
	public String getAddress() {
		return read("address", String.class);
	}

	/**
	 * Sets {@code address}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setAddress(String value) {
		put("address", value);
		return this;
	}

	/**
	 * API field {@code inn}; required. Absent values return null.
	 */
	public String getInn() {
		return read("inn", String.class);
	}

	/**
	 * Sets {@code inn}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setInn(String value) {
		put("inn", value);
		return this;
	}

	/**
	 * API field {@code bank_name}; required. Absent values return null.
	 */
	public String getBankName() {
		return read("bank_name", String.class);
	}

	/**
	 * Sets {@code bank_name}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setBankName(String value) {
		put("bank_name", value);
		return this;
	}

	/**
	 * API field {@code bank_branch}; required. Absent values return null.
	 */
	public String getBankBranch() {
		return read("bank_branch", String.class);
	}

	/**
	 * Sets {@code bank_branch}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setBankBranch(String value) {
		put("bank_branch", value);
		return this;
	}

	/**
	 * API field {@code bank_bik}; required. Absent values return null.
	 */
	public String getBankBik() {
		return read("bank_bik", String.class);
	}

	/**
	 * Sets {@code bank_bik}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setBankBik(String value) {
		put("bank_bik", value);
		return this;
	}

	/**
	 * API field {@code account}; required. Absent values return null.
	 */
	public String getAccount() {
		return read("account", String.class);
	}

	/**
	 * Sets {@code account}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setAccount(String value) {
		put("account", value);
		return this;
	}

	/**
	 * API field {@code kpp}; optional. Absent values return null.
	 */
	public String getKpp() {
		return read("kpp", String.class);
	}

	/**
	 * Sets {@code kpp}; null removes the field.
	 */
	public B2bSberbankPayerBankDetails setKpp(String value) {
		put("kpp", value);
		return this;
	}
}
