// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the B2bSberbankVatData schema. See the pinned OpenAPI specification.
 */
public class B2bSberbankVatData extends JsonModel {
	public B2bSberbankVatData() {
		super();
	}

	public B2bSberbankVatData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CALCULATED = "calculated";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_UNTAXED = "untaxed";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MIXED = "mixed";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public B2bSberbankVatData setType(String value) {
		put("type", value);
		return this;
	}
}
