// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the B2bSberbankMixedVatData schema. See the pinned OpenAPI specification.
 */
public class B2bSberbankMixedVatData extends JsonModel {
	public B2bSberbankMixedVatData() {
		super();
	}

	public B2bSberbankMixedVatData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CALCULATED = "calculated";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_UNTAXED = "untaxed";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MIXED = "mixed";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public B2bSberbankMixedVatData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public B2bSberbankMixedVatData setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}
}
