// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the B2bSberbankCalculatedVatData schema. See the pinned OpenAPI specification.
 */
public class B2bSberbankCalculatedVatData extends JsonModel {
	public B2bSberbankCalculatedVatData() {
		super();
	}

	public B2bSberbankCalculatedVatData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CALCULATED = "calculated";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_UNTAXED = "untaxed";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MIXED = "mixed";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public B2bSberbankCalculatedVatData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code rate}; required. Absent values return null.
	 */
	public String getRate() {
		return read("rate", String.class);
	}

	/**
	 * Sets {@code rate}; null removes the field.
	 */
	public B2bSberbankCalculatedVatData setRate(String value) {
		put("rate", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public B2bSberbankCalculatedVatData setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}
}
