// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the BankCardProduct schema. See the pinned OpenAPI specification.
 */
public class BankCardProduct extends JsonModel {
	public BankCardProduct() {
		super();
	}

	public BankCardProduct(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code code}; required. Absent values return null.
	 */
	public String getCode() {
		return read("code", String.class);
	}

	/**
	 * Sets {@code code}; null removes the field.
	 */
	public BankCardProduct setCode(String value) {
		put("code", value);
		return this;
	}

	/**
	 * API field {@code name}; optional. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public BankCardProduct setName(String value) {
		put("name", value);
		return this;
	}
}
