// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CardRequestData schema. See the pinned OpenAPI specification.
 */
public class CardRequestData extends JsonModel {
	public CardRequestData() {
		super();
	}

	public CardRequestData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code number}; required. Absent values return null.
	 */
	public String getNumber() {
		return read("number", String.class);
	}

	/**
	 * Sets {@code number}; null removes the field.
	 */
	public CardRequestData setNumber(String value) {
		put("number", value);
		return this;
	}

	/**
	 * API field {@code expiry_year}; required. Absent values return null.
	 */
	public String getExpiryYear() {
		return read("expiry_year", String.class);
	}

	/**
	 * Sets {@code expiry_year}; null removes the field.
	 */
	public CardRequestData setExpiryYear(String value) {
		put("expiry_year", value);
		return this;
	}

	/**
	 * API field {@code expiry_month}; required. Absent values return null.
	 */
	public String getExpiryMonth() {
		return read("expiry_month", String.class);
	}

	/**
	 * Sets {@code expiry_month}; null removes the field.
	 */
	public CardRequestData setExpiryMonth(String value) {
		put("expiry_month", value);
		return this;
	}

	/**
	 * API field {@code cardholder}; optional. Absent values return null.
	 */
	public String getCardholder() {
		return read("cardholder", String.class);
	}

	/**
	 * Sets {@code cardholder}; null removes the field.
	 */
	public CardRequestData setCardholder(String value) {
		put("cardholder", value);
		return this;
	}
}
