// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CardDataForPayoutDestination schema. See the pinned OpenAPI specification.
 */
public class CardDataForPayoutDestination extends JsonModel {
	public CardDataForPayoutDestination() {
		super();
	}

	public CardDataForPayoutDestination(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code number}; required. Absent values return null.
	 */
	public String getNumber() {
		return read("number", String.class);
	}

	/**
	 * Sets {@code number}; null removes the field.
	 */
	public CardDataForPayoutDestination setNumber(String value) {
		put("number", value);
		return this;
	}
}
