// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ConfirmationEmbedded schema. See the pinned OpenAPI specification.
 */
public class ConfirmationEmbedded extends JsonModel {
	public ConfirmationEmbedded() {
		super();
	}

	public ConfirmationEmbedded(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EXTERNAL = "external";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMBEDDED = "embedded";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_APPLICATION = "mobile_application";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ConfirmationEmbedded setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code confirmation_token}; required. Absent values return null.
	 */
	public String getConfirmationToken() {
		return read("confirmation_token", String.class);
	}

	/**
	 * Sets {@code confirmation_token}; null removes the field.
	 */
	public ConfirmationEmbedded setConfirmationToken(String value) {
		put("confirmation_token", value);
		return this;
	}
}
