// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ConfirmationQr schema. See the pinned OpenAPI specification.
 */
public class ConfirmationQr extends JsonModel {
	public ConfirmationQr() {
		super();
	}

	public ConfirmationQr(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EXTERNAL = "external";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMBEDDED = "embedded";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_APPLICATION = "mobile_application";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ConfirmationQr setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code confirmation_data}; required. Absent values return null.
	 */
	public String getConfirmationData() {
		return read("confirmation_data", String.class);
	}

	/**
	 * Sets {@code confirmation_data}; null removes the field.
	 */
	public ConfirmationQr setConfirmationData(String value) {
		put("confirmation_data", value);
		return this;
	}
}
