// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ConfirmationDataEmbedded schema. See the pinned OpenAPI specification.
 */
public class ConfirmationDataEmbedded extends JsonModel {
	public ConfirmationDataEmbedded() {
		super();
	}

	public ConfirmationDataEmbedded(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EXTERNAL = "external";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMBEDDED = "embedded";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_APPLICATION = "mobile_application";
	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_RU_RU = "ru_RU";
	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_EN_US = "en_US";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ConfirmationDataEmbedded setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code locale}; optional. Absent values return null.
	 */
	public String getLocale() {
		return read("locale", String.class);
	}

	/**
	 * Sets {@code locale}; null removes the field.
	 */
	public ConfirmationDataEmbedded setLocale(String value) {
		put("locale", value);
		return this;
	}
}
