// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ConfirmationRedirect schema. See the pinned OpenAPI specification.
 */
public class ConfirmationRedirect extends JsonModel {
	public ConfirmationRedirect() {
		super();
	}

	public ConfirmationRedirect(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EXTERNAL = "external";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMBEDDED = "embedded";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_APPLICATION = "mobile_application";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ConfirmationRedirect setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code enforce}; optional. Absent values return null.
	 */
	public Boolean getEnforce() {
		return read("enforce", Boolean.class);
	}

	/**
	 * Sets {@code enforce}; null removes the field.
	 */
	public ConfirmationRedirect setEnforce(Boolean value) {
		put("enforce", value);
		return this;
	}

	/**
	 * API field {@code return_url}; optional. Absent values return null.
	 */
	public String getReturnUrl() {
		return read("return_url", String.class);
	}

	/**
	 * Sets {@code return_url}; null removes the field.
	 */
	public ConfirmationRedirect setReturnUrl(String value) {
		put("return_url", value);
		return this;
	}

	/**
	 * API field {@code confirmation_url}; required. Absent values return null.
	 */
	public String getConfirmationUrl() {
		return read("confirmation_url", String.class);
	}

	/**
	 * Sets {@code confirmation_url}; null removes the field.
	 */
	public ConfirmationRedirect setConfirmationUrl(String value) {
		put("confirmation_url", value);
		return this;
	}
}
