// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CreatePaymentRequest schema. See the pinned OpenAPI specification.
 */
public class CreatePaymentRequest extends JsonModel {
	public CreatePaymentRequest() {
		super();
	}

	public CreatePaymentRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public CreatePaymentRequest setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public CreatePaymentRequest setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code receipt}; optional. Absent values return null.
	 */
	public ReceiptData getReceipt() {
		return read("receipt", ReceiptData.class);
	}

	/**
	 * Sets {@code receipt}; null removes the field.
	 */
	public CreatePaymentRequest setReceipt(ReceiptData value) {
		put("receipt", value);
		return this;
	}

	/**
	 * API field {@code recipient}; optional. Absent values return null.
	 */
	public Recipient getRecipient() {
		return read("recipient", Recipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public CreatePaymentRequest setRecipient(Recipient value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code payment_token}; optional. Absent values return null.
	 */
	public String getPaymentToken() {
		return read("payment_token", String.class);
	}

	/**
	 * Sets {@code payment_token}; null removes the field.
	 */
	public CreatePaymentRequest setPaymentToken(String value) {
		put("payment_token", value);
		return this;
	}

	/**
	 * API field {@code payment_method_id}; optional. Absent values return null.
	 */
	public String getPaymentMethodId() {
		return read("payment_method_id", String.class);
	}

	/**
	 * Sets {@code payment_method_id}; null removes the field.
	 */
	public CreatePaymentRequest setPaymentMethodId(String value) {
		put("payment_method_id", value);
		return this;
	}

	/**
	 * API field {@code payment_method_data}; optional. Absent values return null.
	 */
	public JsonModel getPaymentMethodData() {
		return read("payment_method_data", JsonModel.class);
	}

	/**
	 * Sets {@code payment_method_data}; null removes the field.
	 */
	public CreatePaymentRequest setPaymentMethodData(JsonModel value) {
		put("payment_method_data", value);
		return this;
	}

	/**
	 * API field {@code confirmation}; optional. Absent values return null.
	 */
	public JsonModel getConfirmation() {
		return read("confirmation", JsonModel.class);
	}

	/**
	 * Sets {@code confirmation}; null removes the field.
	 */
	public CreatePaymentRequest setConfirmation(JsonModel value) {
		put("confirmation", value);
		return this;
	}

	/**
	 * API field {@code save_payment_method}; optional. Absent values return null.
	 */
	public Boolean getSavePaymentMethod() {
		return read("save_payment_method", Boolean.class);
	}

	/**
	 * Sets {@code save_payment_method}; null removes the field.
	 */
	public CreatePaymentRequest setSavePaymentMethod(Boolean value) {
		put("save_payment_method", value);
		return this;
	}

	/**
	 * API field {@code capture}; optional. Absent values return null.
	 */
	public Boolean getCapture() {
		return read("capture", Boolean.class);
	}

	/**
	 * Sets {@code capture}; null removes the field.
	 */
	public CreatePaymentRequest setCapture(Boolean value) {
		put("capture", value);
		return this;
	}

	/**
	 * API field {@code client_ip}; optional. Absent values return null.
	 */
	public String getClientIp() {
		return read("client_ip", String.class);
	}

	/**
	 * Sets {@code client_ip}; null removes the field.
	 */
	public CreatePaymentRequest setClientIp(String value) {
		put("client_ip", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public CreatePaymentRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code airline}; optional. Absent values return null.
	 */
	public Airline getAirline() {
		return read("airline", Airline.class);
	}

	/**
	 * Sets {@code airline}; null removes the field.
	 */
	public CreatePaymentRequest setAirline(Airline value) {
		put("airline", value);
		return this;
	}

	/**
	 * API field {@code transfers}; optional. Absent values return null.
	 */
	public java.util.List<TransferDataPayment> getTransfers() {
		return read("transfers", new com.google.gson.reflect.TypeToken<java.util.List<TransferDataPayment>>() {
		}.getType());
	}

	/**
	 * Sets {@code transfers}; null removes the field.
	 */
	public CreatePaymentRequest setTransfers(java.util.List<TransferDataPayment> value) {
		put("transfers", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public PaymentDealInfo getDeal() {
		return read("deal", PaymentDealInfo.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public CreatePaymentRequest setDeal(PaymentDealInfo value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code merchant_customer_id}; optional. Absent values return null.
	 */
	public String getMerchantCustomerId() {
		return read("merchant_customer_id", String.class);
	}

	/**
	 * Sets {@code merchant_customer_id}; null removes the field.
	 */
	public CreatePaymentRequest setMerchantCustomerId(String value) {
		put("merchant_customer_id", value);
		return this;
	}

	/**
	 * API field {@code payment_order}; optional. Absent values return null.
	 */
	public JsonModel getPaymentOrder() {
		return read("payment_order", JsonModel.class);
	}

	/**
	 * Sets {@code payment_order}; null removes the field.
	 */
	public CreatePaymentRequest setPaymentOrder(JsonModel value) {
		put("payment_order", value);
		return this;
	}

	/**
	 * API field {@code receiver}; optional. Absent values return null.
	 */
	public JsonModel getReceiver() {
		return read("receiver", JsonModel.class);
	}

	/**
	 * Sets {@code receiver}; null removes the field.
	 */
	public CreatePaymentRequest setReceiver(JsonModel value) {
		put("receiver", value);
		return this;
	}

	/**
	 * API field {@code statements}; optional. Absent values return null.
	 */
	public java.util.List<JsonModel> getStatements() {
		return read("statements", new com.google.gson.reflect.TypeToken<java.util.List<JsonModel>>() {
		}.getType());
	}

	/**
	 * Sets {@code statements}; null removes the field.
	 */
	public CreatePaymentRequest setStatements(java.util.List<JsonModel> value) {
		put("statements", value);
		return this;
	}

	/**
	 * API field {@code pos_link}; optional. Absent values return null.
	 */
	public PosLinkPaymentData getPosLink() {
		return read("pos_link", PosLinkPaymentData.class);
	}

	/**
	 * Sets {@code pos_link}; null removes the field.
	 */
	public CreatePaymentRequest setPosLink(PosLinkPaymentData value) {
		put("pos_link", value);
		return this;
	}
}
