// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CreatePosLinkRequest schema. See the pinned OpenAPI specification.
 */
public class CreatePosLinkRequest extends JsonModel {
	public CreatePosLinkRequest() {
		super();
	}

	public CreatePosLinkRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code recipient}; required. Absent values return null.
	 */
	public Recipient getRecipient() {
		return read("recipient", Recipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public CreatePosLinkRequest setRecipient(Recipient value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code pos_link_data}; required. Absent values return null.
	 */
	public PosLinkData getPosLinkData() {
		return read("pos_link_data", PosLinkData.class);
	}

	/**
	 * Sets {@code pos_link_data}; null removes the field.
	 */
	public CreatePosLinkRequest setPosLinkData(PosLinkData value) {
		put("pos_link_data", value);
		return this;
	}
}
