// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CreateInvoiceRequest schema. See the pinned OpenAPI specification.
 */
public class CreateInvoiceRequest extends JsonModel {
	public CreateInvoiceRequest() {
		super();
	}

	public CreateInvoiceRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_RU_RU = "ru_RU";
	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_EN_US = "en_US";

	/**
	 * API field {@code payment_data}; required. Absent values return null.
	 */
	public PaymentData getPaymentData() {
		return read("payment_data", PaymentData.class);
	}

	/**
	 * Sets {@code payment_data}; null removes the field.
	 */
	public CreateInvoiceRequest setPaymentData(PaymentData value) {
		put("payment_data", value);
		return this;
	}

	/**
	 * API field {@code cart}; required. Absent values return null.
	 */
	public java.util.List<LineItem> getCart() {
		return read("cart", new com.google.gson.reflect.TypeToken<java.util.List<LineItem>>() {
		}.getType());
	}

	/**
	 * Sets {@code cart}; null removes the field.
	 */
	public CreateInvoiceRequest setCart(java.util.List<LineItem> value) {
		put("cart", value);
		return this;
	}

	/**
	 * API field {@code delivery_method_data}; optional. Absent values return null.
	 */
	public JsonModel getDeliveryMethodData() {
		return read("delivery_method_data", JsonModel.class);
	}

	/**
	 * Sets {@code delivery_method_data}; null removes the field.
	 */
	public CreateInvoiceRequest setDeliveryMethodData(JsonModel value) {
		put("delivery_method_data", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; required. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public CreateInvoiceRequest setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public CreateInvoiceRequest setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}

	/**
	 * API field {@code locale}; optional. Absent values return null.
	 */
	public String getLocale() {
		return read("locale", String.class);
	}

	/**
	 * Sets {@code locale}; null removes the field.
	 */
	public CreateInvoiceRequest setLocale(String value) {
		put("locale", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public CreateInvoiceRequest setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public CreateInvoiceRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
