// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the CreateWebhookRequest schema. See the pinned OpenAPI specification.
 */
public class CreateWebhookRequest extends JsonModel {
	public CreateWebhookRequest() {
		super();
	}

	public CreateWebhookRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code event}. The API may return values added later.
	 */
	public static final String EVENT_PAYMENT_WAITING_FOR_CAPTURE = "payment.waiting_for_capture";
	/**
	 * Documented value of {@code event}. The API may return values added later.
	 */
	public static final String EVENT_PAYMENT_SUCCEEDED = "payment.succeeded";
	/**
	 * Documented value of {@code event}. The API may return values added later.
	 */
	public static final String EVENT_PAYMENT_CANCELED = "payment.canceled";
	/**
	 * Documented value of {@code event}. The API may return values added later.
	 */
	public static final String EVENT_REFUND_SUCCEEDED = "refund.succeeded";
	/**
	 * Documented value of {@code event}. The API may return values added later.
	 */
	public static final String EVENT_PAYMENT_METHOD_ACTIVE = "payment_method.active";

	/**
	 * API field {@code event}; required. Absent values return null.
	 */
	public String getEvent() {
		return read("event", String.class);
	}

	/**
	 * Sets {@code event}; null removes the field.
	 */
	public CreateWebhookRequest setEvent(String value) {
		put("event", value);
		return this;
	}

	/**
	 * API field {@code url}; required. Absent values return null.
	 */
	public String getUrl() {
		return read("url", String.class);
	}

	/**
	 * Sets {@code url}; null removes the field.
	 */
	public CreateWebhookRequest setUrl(String value) {
		put("url", value);
		return this;
	}
}
