// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the DeliveryMethodDataSelf schema. See the pinned OpenAPI specification.
 */
public class DeliveryMethodDataSelf extends JsonModel {
	public DeliveryMethodDataSelf() {
		super();
	}

	public DeliveryMethodDataSelf(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SELF = "self";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SMS = "sms";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMAIL = "email";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public DeliveryMethodDataSelf setType(String value) {
		put("type", value);
		return this;
	}
}
