// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the DeliveryMethodDataEmail schema. See the pinned OpenAPI specification.
 */
public class DeliveryMethodDataEmail extends JsonModel {
	public DeliveryMethodDataEmail() {
		super();
	}

	public DeliveryMethodDataEmail(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SELF = "self";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SMS = "sms";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMAIL = "email";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public DeliveryMethodDataEmail setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code email}; required. Absent values return null.
	 */
	public String getEmail() {
		return read("email", String.class);
	}

	/**
	 * Sets {@code email}; null removes the field.
	 */
	public DeliveryMethodDataEmail setEmail(String value) {
		put("email", value);
		return this;
	}
}
