// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificatePaymentData schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificatePaymentData extends JsonModel {
	public ElectronicCertificatePaymentData() {
		super();
	}

	public ElectronicCertificatePaymentData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public ElectronicCertificatePaymentData setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code basket_id}; required. Absent values return null.
	 */
	public String getBasketId() {
		return read("basket_id", String.class);
	}

	/**
	 * Sets {@code basket_id}; null removes the field.
	 */
	public ElectronicCertificatePaymentData setBasketId(String value) {
		put("basket_id", value);
		return this;
	}
}
