// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificateApprovedPaymentArticle schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificateApprovedPaymentArticle extends JsonModel {
	public ElectronicCertificateApprovedPaymentArticle() {
		super();
	}

	public ElectronicCertificateApprovedPaymentArticle(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code article_number}; required. Absent values return null.
	 */
	public Long getArticleNumber() {
		return read("article_number", Long.class);
	}

	/**
	 * Sets {@code article_number}; null removes the field.
	 */
	public ElectronicCertificateApprovedPaymentArticle setArticleNumber(Long value) {
		put("article_number", value);
		return this;
	}

	/**
	 * API field {@code tru_code}; required. Absent values return null.
	 */
	public String getTruCode() {
		return read("tru_code", String.class);
	}

	/**
	 * Sets {@code tru_code}; null removes the field.
	 */
	public ElectronicCertificateApprovedPaymentArticle setTruCode(String value) {
		put("tru_code", value);
		return this;
	}

	/**
	 * API field {@code article_code}; optional. Absent values return null.
	 */
	public String getArticleCode() {
		return read("article_code", String.class);
	}

	/**
	 * Sets {@code article_code}; null removes the field.
	 */
	public ElectronicCertificateApprovedPaymentArticle setArticleCode(String value) {
		put("article_code", value);
		return this;
	}

	/**
	 * API field {@code certificates}; required. Absent values return null.
	 */
	public java.util.List<ElectronicCertificate> getCertificates() {
		return read("certificates", new com.google.gson.reflect.TypeToken<java.util.List<ElectronicCertificate>>() {
		}.getType());
	}

	/**
	 * Sets {@code certificates}; null removes the field.
	 */
	public ElectronicCertificateApprovedPaymentArticle setCertificates(java.util.List<ElectronicCertificate> value) {
		put("certificates", value);
		return this;
	}
}
