// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificateArticle schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificateArticle extends JsonModel {
	public ElectronicCertificateArticle() {
		super();
	}

	public ElectronicCertificateArticle(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code article_number}; required. Absent values return null.
	 */
	public Long getArticleNumber() {
		return read("article_number", Long.class);
	}

	/**
	 * Sets {@code article_number}; null removes the field.
	 */
	public ElectronicCertificateArticle setArticleNumber(Long value) {
		put("article_number", value);
		return this;
	}

	/**
	 * API field {@code tru_code}; required. Absent values return null.
	 */
	public String getTruCode() {
		return read("tru_code", String.class);
	}

	/**
	 * Sets {@code tru_code}; null removes the field.
	 */
	public ElectronicCertificateArticle setTruCode(String value) {
		put("tru_code", value);
		return this;
	}

	/**
	 * API field {@code article_code}; optional. Absent values return null.
	 */
	public String getArticleCode() {
		return read("article_code", String.class);
	}

	/**
	 * Sets {@code article_code}; null removes the field.
	 */
	public ElectronicCertificateArticle setArticleCode(String value) {
		put("article_code", value);
		return this;
	}

	/**
	 * API field {@code article_name}; required. Absent values return null.
	 */
	public String getArticleName() {
		return read("article_name", String.class);
	}

	/**
	 * Sets {@code article_name}; null removes the field.
	 */
	public ElectronicCertificateArticle setArticleName(String value) {
		put("article_name", value);
		return this;
	}

	/**
	 * API field {@code quantity}; required. Absent values return null.
	 */
	public Long getQuantity() {
		return read("quantity", Long.class);
	}

	/**
	 * Sets {@code quantity}; null removes the field.
	 */
	public ElectronicCertificateArticle setQuantity(Long value) {
		put("quantity", value);
		return this;
	}

	/**
	 * API field {@code price}; required. Absent values return null.
	 */
	public MonetaryAmount getPrice() {
		return read("price", MonetaryAmount.class);
	}

	/**
	 * Sets {@code price}; null removes the field.
	 */
	public ElectronicCertificateArticle setPrice(MonetaryAmount value) {
		put("price", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public ElectronicCertificateArticle setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
