// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificate schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificate extends JsonModel {
	public ElectronicCertificate() {
		super();
	}

	public ElectronicCertificate(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code certificate_id}; required. Absent values return null.
	 */
	public String getCertificateId() {
		return read("certificate_id", String.class);
	}

	/**
	 * Sets {@code certificate_id}; null removes the field.
	 */
	public ElectronicCertificate setCertificateId(String value) {
		put("certificate_id", value);
		return this;
	}

	/**
	 * API field {@code tru_quantity}; required. Absent values return null.
	 */
	public Long getTruQuantity() {
		return read("tru_quantity", Long.class);
	}

	/**
	 * Sets {@code tru_quantity}; null removes the field.
	 */
	public ElectronicCertificate setTruQuantity(Long value) {
		put("tru_quantity", value);
		return this;
	}

	/**
	 * API field {@code available_compensation}; required. Absent values return null.
	 */
	public MonetaryAmount getAvailableCompensation() {
		return read("available_compensation", MonetaryAmount.class);
	}

	/**
	 * Sets {@code available_compensation}; null removes the field.
	 */
	public ElectronicCertificate setAvailableCompensation(MonetaryAmount value) {
		put("available_compensation", value);
		return this;
	}

	/**
	 * API field {@code applied_compensation}; required. Absent values return null.
	 */
	public MonetaryAmount getAppliedCompensation() {
		return read("applied_compensation", MonetaryAmount.class);
	}

	/**
	 * Sets {@code applied_compensation}; null removes the field.
	 */
	public ElectronicCertificate setAppliedCompensation(MonetaryAmount value) {
		put("applied_compensation", value);
		return this;
	}
}
