// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificateRefundMethod schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificateRefundMethod extends JsonModel {
	public ElectronicCertificateRefundMethod() {
		super();
	}

	public ElectronicCertificateRefundMethod(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ELECTRONIC_CERTIFICATE = "electronic_certificate";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ElectronicCertificateRefundMethod setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code electronic_certificate}; optional. Absent values return null.
	 */
	public ElectronicCertificateRefundDataResponse getElectronicCertificate() {
		return read("electronic_certificate", ElectronicCertificateRefundDataResponse.class);
	}

	/**
	 * Sets {@code electronic_certificate}; null removes the field.
	 */
	public ElectronicCertificateRefundMethod setElectronicCertificate(ElectronicCertificateRefundDataResponse value) {
		put("electronic_certificate", value);
		return this;
	}

	/**
	 * API field {@code articles}; optional. Absent values return null.
	 */
	public java.util.List<ElectronicCertificateRefundArticle> getArticles() {
		return read("articles", new com.google.gson.reflect.TypeToken<java.util.List<ElectronicCertificateRefundArticle>>() {
		}.getType());
	}

	/**
	 * Sets {@code articles}; null removes the field.
	 */
	public ElectronicCertificateRefundMethod setArticles(java.util.List<ElectronicCertificateRefundArticle> value) {
		put("articles", value);
		return this;
	}
}
