// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ElectronicCertificateRefundArticle schema. See the pinned OpenAPI specification.
 */
public class ElectronicCertificateRefundArticle extends JsonModel {
	public ElectronicCertificateRefundArticle() {
		super();
	}

	public ElectronicCertificateRefundArticle(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code article_number}; required. Absent values return null.
	 */
	public Long getArticleNumber() {
		return read("article_number", Long.class);
	}

	/**
	 * Sets {@code article_number}; null removes the field.
	 */
	public ElectronicCertificateRefundArticle setArticleNumber(Long value) {
		put("article_number", value);
		return this;
	}

	/**
	 * API field {@code payment_article_number}; required. Absent values return null.
	 */
	public Long getPaymentArticleNumber() {
		return read("payment_article_number", Long.class);
	}

	/**
	 * Sets {@code payment_article_number}; null removes the field.
	 */
	public ElectronicCertificateRefundArticle setPaymentArticleNumber(Long value) {
		put("payment_article_number", value);
		return this;
	}

	/**
	 * API field {@code tru_code}; required. Absent values return null.
	 */
	public String getTruCode() {
		return read("tru_code", String.class);
	}

	/**
	 * Sets {@code tru_code}; null removes the field.
	 */
	public ElectronicCertificateRefundArticle setTruCode(String value) {
		put("tru_code", value);
		return this;
	}

	/**
	 * API field {@code quantity}; required. Absent values return null.
	 */
	public Long getQuantity() {
		return read("quantity", Long.class);
	}

	/**
	 * Sets {@code quantity}; null removes the field.
	 */
	public ElectronicCertificateRefundArticle setQuantity(Long value) {
		put("quantity", value);
		return this;
	}
}
