// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the FiscalizationData schema. See the pinned OpenAPI specification.
 */
public class FiscalizationData extends JsonModel {
	public FiscalizationData() {
		super();
	}

	public FiscalizationData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_ATOL = "atol";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_AVANPOST = "avanpost";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_A_QSI = "a_qsi";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_BUSINESS_RU = "business_ru";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_DIGITAL_KASSA = "digital_kassa";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_EVOTOR = "evotor";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_FIRST_OFD = "first_ofd";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_KIT_INVEST = "kit_invest";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_KOMTET = "komtet";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_LIFE_PAY = "life_pay";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_MERTRADE = "mertrade";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_MODUL_KASSA = "modul_kassa";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_ROCKET = "rocket";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_SHTRIH_M = "shtrih_m";
	/**
	 * Documented value of {@code provider}. The API may return values added later.
	 */
	public static final String PROVIDER_YOO_RECEIPT = "yoo_receipt";

	/**
	 * API field {@code enabled}; required. Absent values return null.
	 */
	public Boolean getEnabled() {
		return read("enabled", Boolean.class);
	}

	/**
	 * Sets {@code enabled}; null removes the field.
	 */
	public FiscalizationData setEnabled(Boolean value) {
		put("enabled", value);
		return this;
	}

	/**
	 * API field {@code provider}; required. Absent values return null.
	 */
	public String getProvider() {
		return read("provider", String.class);
	}

	/**
	 * Sets {@code provider}; null removes the field.
	 */
	public FiscalizationData setProvider(String value) {
		put("provider", value);
		return this;
	}
}
