// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetDealsQuery schema. See the pinned OpenAPI specification.
 */
public class GetDealsQuery extends JsonModel {
	public GetDealsQuery() {
		super();
	}

	public GetDealsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_OPENED = "opened";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CLOSED = "closed";

	/**
	 * API field {@code created_at.gte}; optional. Absent values return null.
	 */
	public String getCreatedAtGte() {
		return read("created_at.gte", String.class);
	}

	/**
	 * Sets {@code created_at.gte}; null removes the field.
	 */
	public GetDealsQuery setCreatedAtGte(String value) {
		put("created_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGteAsDateTime() {
		return readDateTime("created_at.gte");
	}

	/**
	 * Sets {@code created_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setCreatedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gte", value);
		return this;
	}

	/**
	 * API field {@code created_at.gt}; optional. Absent values return null.
	 */
	public String getCreatedAtGt() {
		return read("created_at.gt", String.class);
	}

	/**
	 * Sets {@code created_at.gt}; null removes the field.
	 */
	public GetDealsQuery setCreatedAtGt(String value) {
		put("created_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGtAsDateTime() {
		return readDateTime("created_at.gt");
	}

	/**
	 * Sets {@code created_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setCreatedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gt", value);
		return this;
	}

	/**
	 * API field {@code created_at.lte}; optional. Absent values return null.
	 */
	public String getCreatedAtLte() {
		return read("created_at.lte", String.class);
	}

	/**
	 * Sets {@code created_at.lte}; null removes the field.
	 */
	public GetDealsQuery setCreatedAtLte(String value) {
		put("created_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLteAsDateTime() {
		return readDateTime("created_at.lte");
	}

	/**
	 * Sets {@code created_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setCreatedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lte", value);
		return this;
	}

	/**
	 * API field {@code created_at.lt}; optional. Absent values return null.
	 */
	public String getCreatedAtLt() {
		return read("created_at.lt", String.class);
	}

	/**
	 * Sets {@code created_at.lt}; null removes the field.
	 */
	public GetDealsQuery setCreatedAtLt(String value) {
		put("created_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLtAsDateTime() {
		return readDateTime("created_at.lt");
	}

	/**
	 * Sets {@code created_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setCreatedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lt", value);
		return this;
	}

	/**
	 * API field {@code expires_at.gte}; optional. Absent values return null.
	 */
	public String getExpiresAtGte() {
		return read("expires_at.gte", String.class);
	}

	/**
	 * Sets {@code expires_at.gte}; null removes the field.
	 */
	public GetDealsQuery setExpiresAtGte(String value) {
		put("expires_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtGteAsDateTime() {
		return readDateTime("expires_at.gte");
	}

	/**
	 * Sets {@code expires_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setExpiresAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at.gte", value);
		return this;
	}

	/**
	 * API field {@code expires_at.gt}; optional. Absent values return null.
	 */
	public String getExpiresAtGt() {
		return read("expires_at.gt", String.class);
	}

	/**
	 * Sets {@code expires_at.gt}; null removes the field.
	 */
	public GetDealsQuery setExpiresAtGt(String value) {
		put("expires_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtGtAsDateTime() {
		return readDateTime("expires_at.gt");
	}

	/**
	 * Sets {@code expires_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setExpiresAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at.gt", value);
		return this;
	}

	/**
	 * API field {@code expires_at.lte}; optional. Absent values return null.
	 */
	public String getExpiresAtLte() {
		return read("expires_at.lte", String.class);
	}

	/**
	 * Sets {@code expires_at.lte}; null removes the field.
	 */
	public GetDealsQuery setExpiresAtLte(String value) {
		put("expires_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtLteAsDateTime() {
		return readDateTime("expires_at.lte");
	}

	/**
	 * Sets {@code expires_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setExpiresAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at.lte", value);
		return this;
	}

	/**
	 * API field {@code expires_at.lt}; optional. Absent values return null.
	 */
	public String getExpiresAtLt() {
		return read("expires_at.lt", String.class);
	}

	/**
	 * Sets {@code expires_at.lt}; null removes the field.
	 */
	public GetDealsQuery setExpiresAtLt(String value) {
		put("expires_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtLtAsDateTime() {
		return readDateTime("expires_at.lt");
	}

	/**
	 * Sets {@code expires_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetDealsQuery setExpiresAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at.lt", value);
		return this;
	}

	/**
	 * API field {@code status}; optional. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public GetDealsQuery setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code full_text_search}; optional. Absent values return null.
	 */
	public String getFullTextSearch() {
		return read("full_text_search", String.class);
	}

	/**
	 * Sets {@code full_text_search}; null removes the field.
	 */
	public GetDealsQuery setFullTextSearch(String value) {
		put("full_text_search", value);
		return this;
	}

	/**
	 * API field {@code limit}; optional. Absent values return null.
	 */
	public Long getLimit() {
		return read("limit", Long.class);
	}

	/**
	 * Sets {@code limit}; null removes the field.
	 */
	public GetDealsQuery setLimit(Long value) {
		put("limit", value);
		return this;
	}

	/**
	 * API field {@code cursor}; optional. Absent values return null.
	 */
	public String getCursor() {
		return read("cursor", String.class);
	}

	/**
	 * Sets {@code cursor}; null removes the field.
	 */
	public GetDealsQuery setCursor(String value) {
		put("cursor", value);
		return this;
	}
}
