// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetPaymentsQuery schema. See the pinned OpenAPI specification.
 */
public class GetPaymentsQuery extends JsonModel {
	public GetPaymentsQuery() {
		super();
	}

	public GetPaymentsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_CASH = "cash";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_ALFABANK = "alfabank";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_WEBMONEY = "webmoney";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_WECHAT = "wechat";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_APPLE_PAY = "apple_pay";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_GOOGLE_PAY = "google_pay";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_QIWI = "qiwi";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_INSTALLMENTS = "installments";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_SBERBANK = "sberbank";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_B2B_SBERBANK = "b2b_sberbank";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_TINKOFF_BANK = "tinkoff_bank";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_SBP = "sbp";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_SBER_LOAN = "sber_loan";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_ELECTRONIC_CERTIFICATE = "electronic_certificate";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_SBER_BNPL = "sber_bnpl";
	/**
	 * Documented value of {@code payment_method}. The API may return values added later.
	 */
	public static final String PAYMENT_METHOD_ALFA_PAY = "alfa_pay";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_WAITING_FOR_CAPTURE = "waiting_for_capture";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code created_at.gte}; optional. Absent values return null.
	 */
	public String getCreatedAtGte() {
		return read("created_at.gte", String.class);
	}

	/**
	 * Sets {@code created_at.gte}; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtGte(String value) {
		put("created_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGteAsDateTime() {
		return readDateTime("created_at.gte");
	}

	/**
	 * Sets {@code created_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gte", value);
		return this;
	}

	/**
	 * API field {@code created_at.gt}; optional. Absent values return null.
	 */
	public String getCreatedAtGt() {
		return read("created_at.gt", String.class);
	}

	/**
	 * Sets {@code created_at.gt}; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtGt(String value) {
		put("created_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGtAsDateTime() {
		return readDateTime("created_at.gt");
	}

	/**
	 * Sets {@code created_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gt", value);
		return this;
	}

	/**
	 * API field {@code created_at.lte}; optional. Absent values return null.
	 */
	public String getCreatedAtLte() {
		return read("created_at.lte", String.class);
	}

	/**
	 * Sets {@code created_at.lte}; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtLte(String value) {
		put("created_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLteAsDateTime() {
		return readDateTime("created_at.lte");
	}

	/**
	 * Sets {@code created_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lte", value);
		return this;
	}

	/**
	 * API field {@code created_at.lt}; optional. Absent values return null.
	 */
	public String getCreatedAtLt() {
		return read("created_at.lt", String.class);
	}

	/**
	 * Sets {@code created_at.lt}; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtLt(String value) {
		put("created_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLtAsDateTime() {
		return readDateTime("created_at.lt");
	}

	/**
	 * Sets {@code created_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCreatedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lt", value);
		return this;
	}

	/**
	 * API field {@code captured_at.gte}; optional. Absent values return null.
	 */
	public String getCapturedAtGte() {
		return read("captured_at.gte", String.class);
	}

	/**
	 * Sets {@code captured_at.gte}; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtGte(String value) {
		put("captured_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code captured_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCapturedAtGteAsDateTime() {
		return readDateTime("captured_at.gte");
	}

	/**
	 * Sets {@code captured_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("captured_at.gte", value);
		return this;
	}

	/**
	 * API field {@code captured_at.gt}; optional. Absent values return null.
	 */
	public String getCapturedAtGt() {
		return read("captured_at.gt", String.class);
	}

	/**
	 * Sets {@code captured_at.gt}; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtGt(String value) {
		put("captured_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code captured_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCapturedAtGtAsDateTime() {
		return readDateTime("captured_at.gt");
	}

	/**
	 * Sets {@code captured_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("captured_at.gt", value);
		return this;
	}

	/**
	 * API field {@code captured_at.lte}; optional. Absent values return null.
	 */
	public String getCapturedAtLte() {
		return read("captured_at.lte", String.class);
	}

	/**
	 * Sets {@code captured_at.lte}; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtLte(String value) {
		put("captured_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code captured_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCapturedAtLteAsDateTime() {
		return readDateTime("captured_at.lte");
	}

	/**
	 * Sets {@code captured_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("captured_at.lte", value);
		return this;
	}

	/**
	 * API field {@code captured_at.lt}; optional. Absent values return null.
	 */
	public String getCapturedAtLt() {
		return read("captured_at.lt", String.class);
	}

	/**
	 * Sets {@code captured_at.lt}; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtLt(String value) {
		put("captured_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code captured_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCapturedAtLtAsDateTime() {
		return readDateTime("captured_at.lt");
	}

	/**
	 * Sets {@code captured_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPaymentsQuery setCapturedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("captured_at.lt", value);
		return this;
	}

	/**
	 * API field {@code payment_method}; optional. Absent values return null.
	 */
	public String getPaymentMethod() {
		return read("payment_method", String.class);
	}

	/**
	 * Sets {@code payment_method}; null removes the field.
	 */
	public GetPaymentsQuery setPaymentMethod(String value) {
		put("payment_method", value);
		return this;
	}

	/**
	 * API field {@code status}; optional. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public GetPaymentsQuery setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code limit}; optional. Absent values return null.
	 */
	public Long getLimit() {
		return read("limit", Long.class);
	}

	/**
	 * Sets {@code limit}; null removes the field.
	 */
	public GetPaymentsQuery setLimit(Long value) {
		put("limit", value);
		return this;
	}

	/**
	 * API field {@code cursor}; optional. Absent values return null.
	 */
	public String getCursor() {
		return read("cursor", String.class);
	}

	/**
	 * Sets {@code cursor}; null removes the field.
	 */
	public GetPaymentsQuery setCursor(String value) {
		put("cursor", value);
		return this;
	}
}
