// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetPayoutsQuery schema. See the pinned OpenAPI specification.
 */
public class GetPayoutsQuery extends JsonModel {
	public GetPayoutsQuery() {
		super();
	}

	public GetPayoutsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code payout_destination.type}. The API may return values added later.
	 */
	public static final String PAYOUT_DESTINATION_TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code payout_destination.type}. The API may return values added later.
	 */
	public static final String PAYOUT_DESTINATION_TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code payout_destination.type}. The API may return values added later.
	 */
	public static final String PAYOUT_DESTINATION_TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code created_at.gte}; optional. Absent values return null.
	 */
	public String getCreatedAtGte() {
		return read("created_at.gte", String.class);
	}

	/**
	 * Sets {@code created_at.gte}; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtGte(String value) {
		put("created_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGteAsDateTime() {
		return readDateTime("created_at.gte");
	}

	/**
	 * Sets {@code created_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gte", value);
		return this;
	}

	/**
	 * API field {@code created_at.gt}; optional. Absent values return null.
	 */
	public String getCreatedAtGt() {
		return read("created_at.gt", String.class);
	}

	/**
	 * Sets {@code created_at.gt}; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtGt(String value) {
		put("created_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGtAsDateTime() {
		return readDateTime("created_at.gt");
	}

	/**
	 * Sets {@code created_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gt", value);
		return this;
	}

	/**
	 * API field {@code created_at.lte}; optional. Absent values return null.
	 */
	public String getCreatedAtLte() {
		return read("created_at.lte", String.class);
	}

	/**
	 * Sets {@code created_at.lte}; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtLte(String value) {
		put("created_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLteAsDateTime() {
		return readDateTime("created_at.lte");
	}

	/**
	 * Sets {@code created_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lte", value);
		return this;
	}

	/**
	 * API field {@code created_at.lt}; optional. Absent values return null.
	 */
	public String getCreatedAtLt() {
		return read("created_at.lt", String.class);
	}

	/**
	 * Sets {@code created_at.lt}; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtLt(String value) {
		put("created_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLtAsDateTime() {
		return readDateTime("created_at.lt");
	}

	/**
	 * Sets {@code created_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setCreatedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lt", value);
		return this;
	}

	/**
	 * API field {@code succeeded_at.gte}; optional. Absent values return null.
	 */
	public String getSucceededAtGte() {
		return read("succeeded_at.gte", String.class);
	}

	/**
	 * Sets {@code succeeded_at.gte}; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtGte(String value) {
		put("succeeded_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code succeeded_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSucceededAtGteAsDateTime() {
		return readDateTime("succeeded_at.gte");
	}

	/**
	 * Sets {@code succeeded_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("succeeded_at.gte", value);
		return this;
	}

	/**
	 * API field {@code succeeded_at.gt}; optional. Absent values return null.
	 */
	public String getSucceededAtGt() {
		return read("succeeded_at.gt", String.class);
	}

	/**
	 * Sets {@code succeeded_at.gt}; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtGt(String value) {
		put("succeeded_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code succeeded_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSucceededAtGtAsDateTime() {
		return readDateTime("succeeded_at.gt");
	}

	/**
	 * Sets {@code succeeded_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("succeeded_at.gt", value);
		return this;
	}

	/**
	 * API field {@code succeeded_at.lte}; optional. Absent values return null.
	 */
	public String getSucceededAtLte() {
		return read("succeeded_at.lte", String.class);
	}

	/**
	 * Sets {@code succeeded_at.lte}; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtLte(String value) {
		put("succeeded_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code succeeded_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSucceededAtLteAsDateTime() {
		return readDateTime("succeeded_at.lte");
	}

	/**
	 * Sets {@code succeeded_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("succeeded_at.lte", value);
		return this;
	}

	/**
	 * API field {@code succeeded_at.lt}; optional. Absent values return null.
	 */
	public String getSucceededAtLt() {
		return read("succeeded_at.lt", String.class);
	}

	/**
	 * Sets {@code succeeded_at.lt}; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtLt(String value) {
		put("succeeded_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code succeeded_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSucceededAtLtAsDateTime() {
		return readDateTime("succeeded_at.lt");
	}

	/**
	 * Sets {@code succeeded_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetPayoutsQuery setSucceededAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("succeeded_at.lt", value);
		return this;
	}

	/**
	 * API field {@code payout_destination.type}; optional. Absent values return null.
	 */
	public String getPayoutDestinationType() {
		return read("payout_destination.type", String.class);
	}

	/**
	 * Sets {@code payout_destination.type}; null removes the field.
	 */
	public GetPayoutsQuery setPayoutDestinationType(String value) {
		put("payout_destination.type", value);
		return this;
	}

	/**
	 * API field {@code status}; optional. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public GetPayoutsQuery setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code limit}; optional. Absent values return null.
	 */
	public Long getLimit() {
		return read("limit", Long.class);
	}

	/**
	 * Sets {@code limit}; null removes the field.
	 */
	public GetPayoutsQuery setLimit(Long value) {
		put("limit", value);
		return this;
	}

	/**
	 * API field {@code cursor}; optional. Absent values return null.
	 */
	public String getCursor() {
		return read("cursor", String.class);
	}

	/**
	 * Sets {@code cursor}; null removes the field.
	 */
	public GetPayoutsQuery setCursor(String value) {
		put("cursor", value);
		return this;
	}
}
