// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetReceiptsQuery schema. See the pinned OpenAPI specification.
 */
public class GetReceiptsQuery extends JsonModel {
	public GetReceiptsQuery() {
		super();
	}

	public GetReceiptsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code created_at.gte}; optional. Absent values return null.
	 */
	public String getCreatedAtGte() {
		return read("created_at.gte", String.class);
	}

	/**
	 * Sets {@code created_at.gte}; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtGte(String value) {
		put("created_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGteAsDateTime() {
		return readDateTime("created_at.gte");
	}

	/**
	 * Sets {@code created_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gte", value);
		return this;
	}

	/**
	 * API field {@code created_at.gt}; optional. Absent values return null.
	 */
	public String getCreatedAtGt() {
		return read("created_at.gt", String.class);
	}

	/**
	 * Sets {@code created_at.gt}; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtGt(String value) {
		put("created_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGtAsDateTime() {
		return readDateTime("created_at.gt");
	}

	/**
	 * Sets {@code created_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gt", value);
		return this;
	}

	/**
	 * API field {@code created_at.lte}; optional. Absent values return null.
	 */
	public String getCreatedAtLte() {
		return read("created_at.lte", String.class);
	}

	/**
	 * Sets {@code created_at.lte}; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtLte(String value) {
		put("created_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLteAsDateTime() {
		return readDateTime("created_at.lte");
	}

	/**
	 * Sets {@code created_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lte", value);
		return this;
	}

	/**
	 * API field {@code created_at.lt}; optional. Absent values return null.
	 */
	public String getCreatedAtLt() {
		return read("created_at.lt", String.class);
	}

	/**
	 * Sets {@code created_at.lt}; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtLt(String value) {
		put("created_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLtAsDateTime() {
		return readDateTime("created_at.lt");
	}

	/**
	 * Sets {@code created_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public GetReceiptsQuery setCreatedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lt", value);
		return this;
	}

	/**
	 * API field {@code status}; optional. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public GetReceiptsQuery setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code payment_id}; optional. Absent values return null.
	 */
	public String getPaymentId() {
		return read("payment_id", String.class);
	}

	/**
	 * Sets {@code payment_id}; null removes the field.
	 */
	public GetReceiptsQuery setPaymentId(String value) {
		put("payment_id", value);
		return this;
	}

	/**
	 * API field {@code refund_id}; optional. Absent values return null.
	 */
	public String getRefundId() {
		return read("refund_id", String.class);
	}

	/**
	 * Sets {@code refund_id}; null removes the field.
	 */
	public GetReceiptsQuery setRefundId(String value) {
		put("refund_id", value);
		return this;
	}

	/**
	 * API field {@code limit}; optional. Absent values return null.
	 */
	public Long getLimit() {
		return read("limit", Long.class);
	}

	/**
	 * Sets {@code limit}; null removes the field.
	 */
	public GetReceiptsQuery setLimit(Long value) {
		put("limit", value);
		return this;
	}

	/**
	 * API field {@code cursor}; optional. Absent values return null.
	 */
	public String getCursor() {
		return read("cursor", String.class);
	}

	/**
	 * Sets {@code cursor}; null removes the field.
	 */
	public GetReceiptsQuery setCursor(String value) {
		put("cursor", value);
		return this;
	}
}
