// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetSbpBanksResponse schema. See the pinned OpenAPI specification.
 */
public class GetSbpBanksResponse extends JsonModel {
	public GetSbpBanksResponse() {
		super();
	}

	public GetSbpBanksResponse(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_LIST = "list";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public GetSbpBanksResponse setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<SbpParticipantBank> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<SbpParticipantBank>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public GetSbpBanksResponse setItems(java.util.List<SbpParticipantBank> value) {
		put("items", value);
		return this;
	}
}
