// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the GetSettingsQuery schema. See the pinned OpenAPI specification.
 */
public class GetSettingsQuery extends JsonModel {
	public GetSettingsQuery() {
		super();
	}

	public GetSettingsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code on_behalf_of}; optional. Absent values return null.
	 */
	public String getOnBehalfOf() {
		return read("on_behalf_of", String.class);
	}

	/**
	 * Sets {@code on_behalf_of}; null removes the field.
	 */
	public GetSettingsQuery setOnBehalfOf(String value) {
		put("on_behalf_of", value);
		return this;
	}
}
