// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the IncomeReceipt schema. See the pinned OpenAPI specification.
 */
public class IncomeReceipt extends JsonModel {
	public IncomeReceipt() {
		super();
	}

	public IncomeReceipt(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code service_name}; required. Absent values return null.
	 */
	public String getServiceName() {
		return read("service_name", String.class);
	}

	/**
	 * Sets {@code service_name}; null removes the field.
	 */
	public IncomeReceipt setServiceName(String value) {
		put("service_name", value);
		return this;
	}

	/**
	 * API field {@code npd_receipt_id}; optional. Absent values return null.
	 */
	public String getNpdReceiptId() {
		return read("npd_receipt_id", String.class);
	}

	/**
	 * Sets {@code npd_receipt_id}; null removes the field.
	 */
	public IncomeReceipt setNpdReceiptId(String value) {
		put("npd_receipt_id", value);
		return this;
	}

	/**
	 * API field {@code url}; optional. Absent values return null.
	 */
	public String getUrl() {
		return read("url", String.class);
	}

	/**
	 * Sets {@code url}; null removes the field.
	 */
	public IncomeReceipt setUrl(String value) {
		put("url", value);
		return this;
	}

	/**
	 * API field {@code amount}; optional. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public IncomeReceipt setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}
}
