// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the IndustryDetails schema. See the pinned OpenAPI specification.
 */
public class IndustryDetails extends JsonModel {
	public IndustryDetails() {
		super();
	}

	public IndustryDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code federal_id}; required. Absent values return null.
	 */
	public String getFederalId() {
		return read("federal_id", String.class);
	}

	/**
	 * Sets {@code federal_id}; null removes the field.
	 */
	public IndustryDetails setFederalId(String value) {
		put("federal_id", value);
		return this;
	}

	/**
	 * API field {@code document_date}; required. Absent values return null.
	 */
	public String getDocumentDate() {
		return read("document_date", String.class);
	}

	/**
	 * Sets {@code document_date}; null removes the field.
	 */
	public IndustryDetails setDocumentDate(String value) {
		put("document_date", value);
		return this;
	}

	/**
	 * Parsed {@code document_date}.
	 */
	public java.time.LocalDate getDocumentDateAsDate() {
		return readDate("document_date");
	}

	/**
	 * Sets {@code document_date} as an ISO-8601 date; null removes the field.
	 */
	public IndustryDetails setDocumentDateAsDate(java.time.LocalDate value) {
		putDate("document_date", value);
		return this;
	}

	/**
	 * API field {@code document_number}; required. Absent values return null.
	 */
	public String getDocumentNumber() {
		return read("document_number", String.class);
	}

	/**
	 * Sets {@code document_number}; null removes the field.
	 */
	public IndustryDetails setDocumentNumber(String value) {
		put("document_number", value);
		return this;
	}

	/**
	 * API field {@code value}; required. Absent values return null.
	 */
	public String getValue() {
		return read("value", String.class);
	}

	/**
	 * Sets {@code value}; null removes the field.
	 */
	public IndustryDetails setValue(String value) {
		put("value", value);
		return this;
	}
}
