// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the InvoicingBankCardData schema. See the pinned OpenAPI specification.
 */
public class InvoicingBankCardData extends JsonModel {
	public InvoicingBankCardData() {
		super();
	}

	public InvoicingBankCardData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_MASTER_CARD = "MasterCard";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_VISA = "Visa";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_MIR = "Mir";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_UNION_PAY = "UnionPay";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_JCB = "JCB";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_AMERICAN_EXPRESS = "AmericanExpress";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_DINERS_CLUB = "DinersClub";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_DISCOVER_CARD = "DiscoverCard";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_INSTA_PAYMENT = "InstaPayment";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_INSTA_PAYMENT_TM = "InstaPaymentTM";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_LASER = "Laser";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_DANKORT = "Dankort";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_SOLO = "Solo";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_SWITCH = "Switch";
	/**
	 * Documented value of {@code card_type}. The API may return values added later.
	 */
	public static final String CARD_TYPE_UNKNOWN = "Unknown";

	/**
	 * API field {@code first6}; required. Absent values return null.
	 */
	public String getFirst6() {
		return read("first6", String.class);
	}

	/**
	 * Sets {@code first6}; null removes the field.
	 */
	public InvoicingBankCardData setFirst6(String value) {
		put("first6", value);
		return this;
	}

	/**
	 * API field {@code last4}; required. Absent values return null.
	 */
	public String getLast4() {
		return read("last4", String.class);
	}

	/**
	 * Sets {@code last4}; null removes the field.
	 */
	public InvoicingBankCardData setLast4(String value) {
		put("last4", value);
		return this;
	}

	/**
	 * API field {@code expiry_year}; required. Absent values return null.
	 */
	public String getExpiryYear() {
		return read("expiry_year", String.class);
	}

	/**
	 * Sets {@code expiry_year}; null removes the field.
	 */
	public InvoicingBankCardData setExpiryYear(String value) {
		put("expiry_year", value);
		return this;
	}

	/**
	 * API field {@code expiry_month}; required. Absent values return null.
	 */
	public String getExpiryMonth() {
		return read("expiry_month", String.class);
	}

	/**
	 * Sets {@code expiry_month}; null removes the field.
	 */
	public InvoicingBankCardData setExpiryMonth(String value) {
		put("expiry_month", value);
		return this;
	}

	/**
	 * API field {@code card_type}; required. Absent values return null.
	 */
	public String getCardType() {
		return read("card_type", String.class);
	}

	/**
	 * Sets {@code card_type}; null removes the field.
	 */
	public InvoicingBankCardData setCardType(String value) {
		put("card_type", value);
		return this;
	}
}
