// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Invoice schema. See the pinned OpenAPI specification.
 */
public class Invoice extends JsonModel {
	public Invoice() {
		super();
	}

	public Invoice(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public Invoice setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Invoice setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code cart}; required. Absent values return null.
	 */
	public java.util.List<LineItem> getCart() {
		return read("cart", new com.google.gson.reflect.TypeToken<java.util.List<LineItem>>() {
		}.getType());
	}

	/**
	 * Sets {@code cart}; null removes the field.
	 */
	public Invoice setCart(java.util.List<LineItem> value) {
		put("cart", value);
		return this;
	}

	/**
	 * API field {@code delivery_method}; optional. Absent values return null.
	 */
	public JsonModel getDeliveryMethod() {
		return read("delivery_method", JsonModel.class);
	}

	/**
	 * Sets {@code delivery_method}; null removes the field.
	 */
	public Invoice setDeliveryMethod(JsonModel value) {
		put("delivery_method", value);
		return this;
	}

	/**
	 * API field {@code payment_details}; optional. Absent values return null.
	 */
	public PaymentDetails getPaymentDetails() {
		return read("payment_details", PaymentDetails.class);
	}

	/**
	 * Sets {@code payment_details}; null removes the field.
	 */
	public Invoice setPaymentDetails(PaymentDetails value) {
		put("payment_details", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public Invoice setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Invoice setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; optional. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public Invoice setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Invoice setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public Invoice setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code cancellation_details}; optional. Absent values return null.
	 */
	public InvoiceCancellationDetails getCancellationDetails() {
		return read("cancellation_details", InvoiceCancellationDetails.class);
	}

	/**
	 * Sets {@code cancellation_details}; null removes the field.
	 */
	public Invoice setCancellationDetails(InvoiceCancellationDetails value) {
		put("cancellation_details", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public Invoice setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
