// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the InvoiceCancellationDetails schema. See the pinned OpenAPI specification.
 */
public class InvoiceCancellationDetails extends JsonModel {
	public InvoiceCancellationDetails() {
		super();
	}

	public InvoiceCancellationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_MERCHANT = "merchant";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INVOICE_CANCELED = "invoice_canceled";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INVOICE_EXPIRED = "invoice_expired";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_GENERAL_DECLINE = "general_decline";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_CANCELED = "payment_canceled";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_EXPIRED_ON_CAPTURE = "payment_expired_on_capture";

	/**
	 * API field {@code party}; required. Absent values return null.
	 */
	public String getParty() {
		return read("party", String.class);
	}

	/**
	 * Sets {@code party}; null removes the field.
	 */
	public InvoiceCancellationDetails setParty(String value) {
		put("party", value);
		return this;
	}

	/**
	 * API field {@code reason}; required. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public InvoiceCancellationDetails setReason(String value) {
		put("reason", value);
		return this;
	}
}
