// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the LineItem schema. See the pinned OpenAPI specification.
 */
public class LineItem extends JsonModel {
	public LineItem() {
		super();
	}

	public LineItem(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code description}; required. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public LineItem setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code price}; required. Absent values return null.
	 */
	public MonetaryAmount getPrice() {
		return read("price", MonetaryAmount.class);
	}

	/**
	 * Sets {@code price}; null removes the field.
	 */
	public LineItem setPrice(MonetaryAmount value) {
		put("price", value);
		return this;
	}

	/**
	 * API field {@code discount_price}; optional. Absent values return null.
	 */
	public MonetaryAmount getDiscountPrice() {
		return read("discount_price", MonetaryAmount.class);
	}

	/**
	 * Sets {@code discount_price}; null removes the field.
	 */
	public LineItem setDiscountPrice(MonetaryAmount value) {
		put("discount_price", value);
		return this;
	}

	/**
	 * API field {@code quantity}; required. Absent values return null.
	 */
	public java.math.BigDecimal getQuantity() {
		return read("quantity", java.math.BigDecimal.class);
	}

	/**
	 * Sets {@code quantity}; null removes the field.
	 */
	public LineItem setQuantity(java.math.BigDecimal value) {
		put("quantity", value);
		return this;
	}
}
