// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the MarkCodeInfo schema. See the pinned OpenAPI specification.
 */
public class MarkCodeInfo extends JsonModel {
	public MarkCodeInfo() {
		super();
	}

	public MarkCodeInfo(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code mark_code_raw}; optional. Absent values return null.
	 */
	public String getMarkCodeRaw() {
		return read("mark_code_raw", String.class);
	}

	/**
	 * Sets {@code mark_code_raw}; null removes the field.
	 */
	public MarkCodeInfo setMarkCodeRaw(String value) {
		put("mark_code_raw", value);
		return this;
	}

	/**
	 * API field {@code unknown}; optional. Absent values return null.
	 */
	public String getUnknown() {
		return read("unknown", String.class);
	}

	/**
	 * Sets {@code unknown}; null removes the field.
	 */
	public MarkCodeInfo setUnknown(String value) {
		put("unknown", value);
		return this;
	}

	/**
	 * API field {@code ean_8}; optional. Absent values return null.
	 */
	public String getEan8() {
		return read("ean_8", String.class);
	}

	/**
	 * Sets {@code ean_8}; null removes the field.
	 */
	public MarkCodeInfo setEan8(String value) {
		put("ean_8", value);
		return this;
	}

	/**
	 * API field {@code ean_13}; optional. Absent values return null.
	 */
	public String getEan13() {
		return read("ean_13", String.class);
	}

	/**
	 * Sets {@code ean_13}; null removes the field.
	 */
	public MarkCodeInfo setEan13(String value) {
		put("ean_13", value);
		return this;
	}

	/**
	 * API field {@code itf_14}; optional. Absent values return null.
	 */
	public String getItf14() {
		return read("itf_14", String.class);
	}

	/**
	 * Sets {@code itf_14}; null removes the field.
	 */
	public MarkCodeInfo setItf14(String value) {
		put("itf_14", value);
		return this;
	}

	/**
	 * API field {@code gs_10}; optional. Absent values return null.
	 */
	public String getGs10() {
		return read("gs_10", String.class);
	}

	/**
	 * Sets {@code gs_10}; null removes the field.
	 */
	public MarkCodeInfo setGs10(String value) {
		put("gs_10", value);
		return this;
	}

	/**
	 * API field {@code gs_1m}; optional. Absent values return null.
	 */
	public String getGs1m() {
		return read("gs_1m", String.class);
	}

	/**
	 * Sets {@code gs_1m}; null removes the field.
	 */
	public MarkCodeInfo setGs1m(String value) {
		put("gs_1m", value);
		return this;
	}

	/**
	 * API field {@code short}; optional. Absent values return null.
	 */
	public String getShort() {
		return read("short", String.class);
	}

	/**
	 * Sets {@code short}; null removes the field.
	 */
	public MarkCodeInfo setShort(String value) {
		put("short", value);
		return this;
	}

	/**
	 * API field {@code fur}; optional. Absent values return null.
	 */
	public String getFur() {
		return read("fur", String.class);
	}

	/**
	 * Sets {@code fur}; null removes the field.
	 */
	public MarkCodeInfo setFur(String value) {
		put("fur", value);
		return this;
	}

	/**
	 * API field {@code egais_20}; optional. Absent values return null.
	 */
	public String getEgais20() {
		return read("egais_20", String.class);
	}

	/**
	 * Sets {@code egais_20}; null removes the field.
	 */
	public MarkCodeInfo setEgais20(String value) {
		put("egais_20", value);
		return this;
	}

	/**
	 * API field {@code egais_30}; optional. Absent values return null.
	 */
	public String getEgais30() {
		return read("egais_30", String.class);
	}

	/**
	 * Sets {@code egais_30}; null removes the field.
	 */
	public MarkCodeInfo setEgais30(String value) {
		put("egais_30", value);
		return this;
	}
}
