// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the MarkQuantity schema. See the pinned OpenAPI specification.
 */
public class MarkQuantity extends JsonModel {
	public MarkQuantity() {
		super();
	}

	public MarkQuantity(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code numerator}; required. Absent values return null.
	 */
	public Long getNumerator() {
		return read("numerator", Long.class);
	}

	/**
	 * Sets {@code numerator}; null removes the field.
	 */
	public MarkQuantity setNumerator(Long value) {
		put("numerator", value);
		return this;
	}

	/**
	 * API field {@code denominator}; required. Absent values return null.
	 */
	public Long getDenominator() {
		return read("denominator", Long.class);
	}

	/**
	 * Sets {@code denominator}; null removes the field.
	 */
	public MarkQuantity setDenominator(Long value) {
		put("denominator", value);
		return this;
	}
}
