// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Me schema. See the pinned OpenAPI specification.
 */
public class Me extends JsonModel {
	public Me() {
		super();
	}

	public Me(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ENABLED = "enabled";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_DISABLED = "disabled";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_CASH = "cash";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_ALFABANK = "alfabank";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_WEBMONEY = "webmoney";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_WECHAT = "wechat";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_APPLE_PAY = "apple_pay";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_GOOGLE_PAY = "google_pay";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_QIWI = "qiwi";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_INSTALLMENTS = "installments";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_SBERBANK = "sberbank";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_B2B_SBERBANK = "b2b_sberbank";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_TINKOFF_BANK = "tinkoff_bank";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_SBP = "sbp";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_SBER_LOAN = "sber_loan";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_ELECTRONIC_CERTIFICATE = "electronic_certificate";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_SBER_BNPL = "sber_bnpl";
	/**
	 * Documented value of {@code payment_methods}. The API may return values added later.
	 */
	public static final String PAYMENT_METHODS_ALFA_PAY = "alfa_pay";
	/**
	 * Documented value of {@code payout_methods}. The API may return values added later.
	 */
	public static final String PAYOUT_METHODS_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code payout_methods}. The API may return values added later.
	 */
	public static final String PAYOUT_METHODS_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code payout_methods}. The API may return values added later.
	 */
	public static final String PAYOUT_METHODS_SBP = "sbp";

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public Me setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Me setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code test}; required. Absent values return null.
	 */
	public Boolean getTest() {
		return read("test", Boolean.class);
	}

	/**
	 * Sets {@code test}; null removes the field.
	 */
	public Me setTest(Boolean value) {
		put("test", value);
		return this;
	}

	/**
	 * API field {@code fiscalization}; optional. Absent values return null.
	 */
	public FiscalizationData getFiscalization() {
		return read("fiscalization", FiscalizationData.class);
	}

	/**
	 * Sets {@code fiscalization}; null removes the field.
	 */
	public Me setFiscalization(FiscalizationData value) {
		put("fiscalization", value);
		return this;
	}

	/**
	 * API field {@code fiscalization_enabled}; optional. Absent values return null.
	 */
	public Boolean getFiscalizationEnabled() {
		return read("fiscalization_enabled", Boolean.class);
	}

	/**
	 * Sets {@code fiscalization_enabled}; null removes the field.
	 */
	public Me setFiscalizationEnabled(Boolean value) {
		put("fiscalization_enabled", value);
		return this;
	}

	/**
	 * API field {@code payment_methods}; optional. Absent values return null.
	 */
	public java.util.List<String> getPaymentMethods() {
		return read("payment_methods", new com.google.gson.reflect.TypeToken<java.util.List<String>>() {
		}.getType());
	}

	/**
	 * Sets {@code payment_methods}; null removes the field.
	 */
	public Me setPaymentMethods(java.util.List<String> value) {
		put("payment_methods", value);
		return this;
	}

	/**
	 * API field {@code itn}; optional. Absent values return null.
	 */
	public String getItn() {
		return read("itn", String.class);
	}

	/**
	 * Sets {@code itn}; null removes the field.
	 */
	public Me setItn(String value) {
		put("itn", value);
		return this;
	}

	/**
	 * API field {@code payout_methods}; optional. Absent values return null.
	 */
	public java.util.List<String> getPayoutMethods() {
		return read("payout_methods", new com.google.gson.reflect.TypeToken<java.util.List<String>>() {
		}.getType());
	}

	/**
	 * Sets {@code payout_methods}; null removes the field.
	 */
	public Me setPayoutMethods(java.util.List<String> value) {
		put("payout_methods", value);
		return this;
	}

	/**
	 * API field {@code name}; optional. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public Me setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code payout_balance}; optional. Absent values return null.
	 */
	public MonetaryAmount getPayoutBalance() {
		return read("payout_balance", MonetaryAmount.class);
	}

	/**
	 * Sets {@code payout_balance}; null removes the field.
	 */
	public Me setPayoutBalance(MonetaryAmount value) {
		put("payout_balance", value);
		return this;
	}
}
