// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Metadata schema. See the pinned OpenAPI specification.
 */
public class Metadata extends JsonModel {
	public Metadata() {
		super();
	}

	public Metadata(com.google.gson.JsonObject json) {
		super(json);
	}
}
