// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the NotFound schema. See the pinned OpenAPI specification.
 */
public class NotFound extends JsonModel {
	public NotFound() {
		super();
	}

	public NotFound(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ERROR = "error";
	/**
	 * Documented value of {@code code}. The API may return values added later.
	 */
	public static final String CODE_NOT_FOUND = "not_found";

	/**
	 * API field {@code type}; optional. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public NotFound setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; optional. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public NotFound setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public NotFound setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code parameter}; optional. Absent values return null.
	 */
	public String getParameter() {
		return read("parameter", String.class);
	}

	/**
	 * Sets {@code parameter}; null removes the field.
	 */
	public NotFound setParameter(String value) {
		put("parameter", value);
		return this;
	}

	/**
	 * API field {@code retry_after}; optional. Absent values return null.
	 */
	public Long getRetryAfter() {
		return read("retry_after", Long.class);
	}

	/**
	 * Sets {@code retry_after}; null removes the field.
	 */
	public NotFound setRetryAfter(Long value) {
		put("retry_after", value);
		return this;
	}

	/**
	 * API field {@code code}; optional. Absent values return null.
	 */
	public String getCode() {
		return read("code", String.class);
	}

	/**
	 * Sets {@code code}; null removes the field.
	 */
	public NotFound setCode(String value) {
		put("code", value);
		return this;
	}
}
