// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the OperationalDetails schema. See the pinned OpenAPI specification.
 */
public class OperationalDetails extends JsonModel {
	public OperationalDetails() {
		super();
	}

	public OperationalDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code operation_id}; required. Absent values return null.
	 */
	public Long getOperationId() {
		return read("operation_id", Long.class);
	}

	/**
	 * Sets {@code operation_id}; null removes the field.
	 */
	public OperationalDetails setOperationId(Long value) {
		put("operation_id", value);
		return this;
	}

	/**
	 * API field {@code value}; required. Absent values return null.
	 */
	public String getValue() {
		return read("value", String.class);
	}

	/**
	 * Sets {@code value}; null removes the field.
	 */
	public OperationalDetails setValue(String value) {
		put("value", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public OperationalDetails setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public OperationalDetails setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}
}
