// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOrderDataUtilities schema. See the pinned OpenAPI specification.
 */
public class PaymentOrderDataUtilities extends JsonModel {
	public PaymentOrderDataUtilities() {
		super();
	}

	public PaymentOrderDataUtilities(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_UTILITIES = "utilities";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentOrderDataUtilities setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public PaymentOrderDataUtilities setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code payment_purpose}; required. Absent values return null.
	 */
	public String getPaymentPurpose() {
		return read("payment_purpose", String.class);
	}

	/**
	 * Sets {@code payment_purpose}; null removes the field.
	 */
	public PaymentOrderDataUtilities setPaymentPurpose(String value) {
		put("payment_purpose", value);
		return this;
	}

	/**
	 * API field {@code recipient}; required. Absent values return null.
	 */
	public PaymentOrderRecipientUtilities getRecipient() {
		return read("recipient", PaymentOrderRecipientUtilities.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public PaymentOrderDataUtilities setRecipient(PaymentOrderRecipientUtilities value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code kbk}; optional. Absent values return null.
	 */
	public String getKbk() {
		return read("kbk", String.class);
	}

	/**
	 * Sets {@code kbk}; null removes the field.
	 */
	public PaymentOrderDataUtilities setKbk(String value) {
		put("kbk", value);
		return this;
	}

	/**
	 * API field {@code oktmo}; optional. Absent values return null.
	 */
	public String getOktmo() {
		return read("oktmo", String.class);
	}

	/**
	 * Sets {@code oktmo}; null removes the field.
	 */
	public PaymentOrderDataUtilities setOktmo(String value) {
		put("oktmo", value);
		return this;
	}

	/**
	 * API field {@code payment_period}; optional. Absent values return null.
	 */
	public PaymentPeriod getPaymentPeriod() {
		return read("payment_period", PaymentPeriod.class);
	}

	/**
	 * Sets {@code payment_period}; null removes the field.
	 */
	public PaymentOrderDataUtilities setPaymentPeriod(PaymentPeriod value) {
		put("payment_period", value);
		return this;
	}

	/**
	 * API field {@code payment_document_id}; optional. Absent values return null.
	 */
	public String getPaymentDocumentId() {
		return read("payment_document_id", String.class);
	}

	/**
	 * Sets {@code payment_document_id}; null removes the field.
	 */
	public PaymentOrderDataUtilities setPaymentDocumentId(String value) {
		put("payment_document_id", value);
		return this;
	}

	/**
	 * API field {@code payment_document_number}; optional. Absent values return null.
	 */
	public String getPaymentDocumentNumber() {
		return read("payment_document_number", String.class);
	}

	/**
	 * Sets {@code payment_document_number}; null removes the field.
	 */
	public PaymentOrderDataUtilities setPaymentDocumentNumber(String value) {
		put("payment_document_number", value);
		return this;
	}

	/**
	 * API field {@code account_number}; optional. Absent values return null.
	 */
	public String getAccountNumber() {
		return read("account_number", String.class);
	}

	/**
	 * Sets {@code account_number}; null removes the field.
	 */
	public PaymentOrderDataUtilities setAccountNumber(String value) {
		put("account_number", value);
		return this;
	}

	/**
	 * API field {@code unified_account_number}; optional. Absent values return null.
	 */
	public String getUnifiedAccountNumber() {
		return read("unified_account_number", String.class);
	}

	/**
	 * Sets {@code unified_account_number}; null removes the field.
	 */
	public PaymentOrderDataUtilities setUnifiedAccountNumber(String value) {
		put("unified_account_number", value);
		return this;
	}

	/**
	 * API field {@code service_id}; optional. Absent values return null.
	 */
	public String getServiceId() {
		return read("service_id", String.class);
	}

	/**
	 * Sets {@code service_id}; null removes the field.
	 */
	public PaymentOrderDataUtilities setServiceId(String value) {
		put("service_id", value);
		return this;
	}
}
