// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOrderData schema. See the pinned OpenAPI specification.
 */
public class PaymentOrderData extends JsonModel {
	public PaymentOrderData() {
		super();
	}

	public PaymentOrderData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_UTILITIES = "utilities";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentOrderData setType(String value) {
		put("type", value);
		return this;
	}
}
