// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentPeriod schema. See the pinned OpenAPI specification.
 */
public class PaymentPeriod extends JsonModel {
	public PaymentPeriod() {
		super();
	}

	public PaymentPeriod(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code month}; required. Absent values return null.
	 */
	public Long getMonth() {
		return read("month", Long.class);
	}

	/**
	 * Sets {@code month}; null removes the field.
	 */
	public PaymentPeriod setMonth(Long value) {
		put("month", value);
		return this;
	}

	/**
	 * API field {@code year}; required. Absent values return null.
	 */
	public Long getYear() {
		return read("year", Long.class);
	}

	/**
	 * Sets {@code year}; null removes the field.
	 */
	public PaymentPeriod setYear(Long value) {
		put("year", value);
		return this;
	}
}
