// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentCaptureRequestDeal schema. See the pinned OpenAPI specification.
 */
public class PaymentCaptureRequestDeal extends JsonModel {
	public PaymentCaptureRequestDeal() {
		super();
	}

	public PaymentCaptureRequestDeal(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code settlements}; required. Absent values return null.
	 */
	public java.util.List<JsonModel> getSettlements() {
		return read("settlements", new com.google.gson.reflect.TypeToken<java.util.List<JsonModel>>() {
		}.getType());
	}

	/**
	 * Sets {@code settlements}; null removes the field.
	 */
	public PaymentCaptureRequestDeal setSettlements(java.util.List<JsonModel> value) {
		put("settlements", value);
		return this;
	}
}
