// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentCancellationDetails schema. See the pinned OpenAPI specification.
 */
public class PaymentCancellationDetails extends JsonModel {
	public PaymentCancellationDetails() {
		super();
	}

	public PaymentCancellationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_PAYMENT_NETWORK = "payment_network";
	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_MERCHANT = "merchant";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON__3D_SECURE_FAILED = "3d_secure_failed";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_CALL_ISSUER = "call_issuer";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_CARD_EXPIRED = "card_expired";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_METHOD_LIMIT_EXCEEDED = "payment_method_limit_exceeded";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_METHOD_RESTRICTED = "payment_method_restricted";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_COUNTRY_FORBIDDEN = "country_forbidden";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_GENERAL_DECLINE = "general_decline";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_FRAUD_SUSPECTED = "fraud_suspected";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_IDENTIFICATION_REQUIRED = "identification_required";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INSUFFICIENT_FUNDS = "insufficient_funds";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INVALID_CARD_NUMBER = "invalid_card_number";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INVALID_CSC = "invalid_csc";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_ISSUER_UNAVAILABLE = "issuer_unavailable";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_CANCELED_BY_MERCHANT = "canceled_by_merchant";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PERMISSION_REVOKED = "permission_revoked";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INTERNAL_TIMEOUT = "internal_timeout";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_EXPIRED_ON_CONFIRMATION = "expired_on_confirmation";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_EXPIRED_ON_CAPTURE = "expired_on_capture";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_UNSUPPORTED_MOBILE_OPERATOR = "unsupported_mobile_operator";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_DEAL_EXPIRED = "deal_expired";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_LOAN_DECLINED = "loan_declined";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_LOAN_DECLINED_BY_PAYER = "loan_declined_by_payer";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_LOAN_APPLICATION_EXPIRED = "loan_application_expired";

	/**
	 * API field {@code party}; required. Absent values return null.
	 */
	public String getParty() {
		return read("party", String.class);
	}

	/**
	 * Sets {@code party}; null removes the field.
	 */
	public PaymentCancellationDetails setParty(String value) {
		put("party", value);
		return this;
	}

	/**
	 * API field {@code reason}; required. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public PaymentCancellationDetails setReason(String value) {
		put("reason", value);
		return this;
	}
}
