// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOrderRecipientUtilities schema. See the pinned OpenAPI specification.
 */
public class PaymentOrderRecipientUtilities extends JsonModel {
	public PaymentOrderRecipientUtilities() {
		super();
	}

	public PaymentOrderRecipientUtilities(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code name}; required. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public PaymentOrderRecipientUtilities setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code inn}; required. Absent values return null.
	 */
	public String getInn() {
		return read("inn", String.class);
	}

	/**
	 * Sets {@code inn}; null removes the field.
	 */
	public PaymentOrderRecipientUtilities setInn(String value) {
		put("inn", value);
		return this;
	}

	/**
	 * API field {@code kpp}; required. Absent values return null.
	 */
	public String getKpp() {
		return read("kpp", String.class);
	}

	/**
	 * Sets {@code kpp}; null removes the field.
	 */
	public PaymentOrderRecipientUtilities setKpp(String value) {
		put("kpp", value);
		return this;
	}

	/**
	 * API field {@code bank}; required. Absent values return null.
	 */
	public PaymentOrderBankUtilities getBank() {
		return read("bank", PaymentOrderBankUtilities.class);
	}

	/**
	 * Sets {@code bank}; null removes the field.
	 */
	public PaymentOrderRecipientUtilities setBank(PaymentOrderBankUtilities value) {
		put("bank", value);
		return this;
	}
}
