// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentCaptureRequest schema. See the pinned OpenAPI specification.
 */
public class PaymentCaptureRequest extends JsonModel {
	public PaymentCaptureRequest() {
		super();
	}

	public PaymentCaptureRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code amount}; optional. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public PaymentCaptureRequest setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code receipt}; optional. Absent values return null.
	 */
	public ReceiptData getReceipt() {
		return read("receipt", ReceiptData.class);
	}

	/**
	 * Sets {@code receipt}; null removes the field.
	 */
	public PaymentCaptureRequest setReceipt(ReceiptData value) {
		put("receipt", value);
		return this;
	}

	/**
	 * API field {@code airline}; optional. Absent values return null.
	 */
	public Airline getAirline() {
		return read("airline", Airline.class);
	}

	/**
	 * Sets {@code airline}; null removes the field.
	 */
	public PaymentCaptureRequest setAirline(Airline value) {
		put("airline", value);
		return this;
	}

	/**
	 * API field {@code transfers}; optional. Absent values return null.
	 */
	public java.util.List<TransferDataCapture> getTransfers() {
		return read("transfers", new com.google.gson.reflect.TypeToken<java.util.List<TransferDataCapture>>() {
		}.getType());
	}

	/**
	 * Sets {@code transfers}; null removes the field.
	 */
	public PaymentCaptureRequest setTransfers(java.util.List<TransferDataCapture> value) {
		put("transfers", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public PaymentCaptureRequestDeal getDeal() {
		return read("deal", PaymentCaptureRequestDeal.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public PaymentCaptureRequest setDeal(PaymentCaptureRequestDeal value) {
		put("deal", value);
		return this;
	}
}
