// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodsConfirmationDataRedirect schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodsConfirmationDataRedirect extends JsonModel {
	public PaymentMethodsConfirmationDataRedirect() {
		super();
	}

	public PaymentMethodsConfirmationDataRedirect(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";
	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_RU_RU = "ru_RU";
	/**
	 * Documented value of {@code locale}. The API may return values added later.
	 */
	public static final String LOCALE_EN_US = "en_US";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataRedirect setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code enforce}; optional. Absent values return null.
	 */
	public Boolean getEnforce() {
		return read("enforce", Boolean.class);
	}

	/**
	 * Sets {@code enforce}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataRedirect setEnforce(Boolean value) {
		put("enforce", value);
		return this;
	}

	/**
	 * API field {@code return_url}; required. Absent values return null.
	 */
	public String getReturnUrl() {
		return read("return_url", String.class);
	}

	/**
	 * Sets {@code return_url}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataRedirect setReturnUrl(String value) {
		put("return_url", value);
		return this;
	}

	/**
	 * API field {@code locale}; optional. Absent values return null.
	 */
	public String getLocale() {
		return read("locale", String.class);
	}

	/**
	 * Sets {@code locale}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataRedirect setLocale(String value) {
		put("locale", value);
		return this;
	}
}
