// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodsConfirmationDataQr schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodsConfirmationDataQr extends JsonModel {
	public PaymentMethodsConfirmationDataQr() {
		super();
	}

	public PaymentMethodsConfirmationDataQr(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataQr setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code return_url}; optional. Absent values return null.
	 */
	public String getReturnUrl() {
		return read("return_url", String.class);
	}

	/**
	 * Sets {@code return_url}; null removes the field.
	 */
	public PaymentMethodsConfirmationDataQr setReturnUrl(String value) {
		put("return_url", value);
		return this;
	}
}
