// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOrderBankUtilities schema. See the pinned OpenAPI specification.
 */
public class PaymentOrderBankUtilities extends JsonModel {
	public PaymentOrderBankUtilities() {
		super();
	}

	public PaymentOrderBankUtilities(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code name}; required. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public PaymentOrderBankUtilities setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code bic}; required. Absent values return null.
	 */
	public String getBic() {
		return read("bic", String.class);
	}

	/**
	 * Sets {@code bic}; null removes the field.
	 */
	public PaymentOrderBankUtilities setBic(String value) {
		put("bic", value);
		return this;
	}

	/**
	 * API field {@code account}; required. Absent values return null.
	 */
	public String getAccount() {
		return read("account", String.class);
	}

	/**
	 * Sets {@code account}; null removes the field.
	 */
	public PaymentOrderBankUtilities setAccount(String value) {
		put("account", value);
		return this;
	}

	/**
	 * API field {@code correspondent_account}; required. Absent values return null.
	 */
	public String getCorrespondentAccount() {
		return read("correspondent_account", String.class);
	}

	/**
	 * Sets {@code correspondent_account}; null removes the field.
	 */
	public PaymentOrderBankUtilities setCorrespondentAccount(String value) {
		put("correspondent_account", value);
		return this;
	}
}
