// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOverviewStatementData schema. See the pinned OpenAPI specification.
 */
public class PaymentOverviewStatementData extends JsonModel {
	public PaymentOverviewStatementData() {
		super();
	}

	public PaymentOverviewStatementData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYMENT_OVERVIEW = "payment_overview";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentOverviewStatementData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code delivery_method}; required. Absent values return null.
	 */
	public JsonModel getDeliveryMethod() {
		return read("delivery_method", JsonModel.class);
	}

	/**
	 * Sets {@code delivery_method}; null removes the field.
	 */
	public PaymentOverviewStatementData setDeliveryMethod(JsonModel value) {
		put("delivery_method", value);
		return this;
	}
}
