// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodElectronicCertificate schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodElectronicCertificate extends JsonModel {
	public PaymentMethodElectronicCertificate() {
		super();
	}

	public PaymentMethodElectronicCertificate(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CASH = "cash";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ALFABANK = "alfabank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_WEBMONEY = "webmoney";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_WECHAT = "wechat";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_APPLE_PAY = "apple_pay";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_GOOGLE_PAY = "google_pay";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QIWI = "qiwi";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_INSTALLMENTS = "installments";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBERBANK = "sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_B2B_SBERBANK = "b2b_sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_TINKOFF_BANK = "tinkoff_bank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_LOAN = "sber_loan";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ELECTRONIC_CERTIFICATE = "electronic_certificate";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_BNPL = "sber_bnpl";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ALFA_PAY = "alfa_pay";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ACTIVE = "active";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_INACTIVE = "inactive";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code saved}; required. Absent values return null.
	 */
	public Boolean getSaved() {
		return read("saved", Boolean.class);
	}

	/**
	 * Sets {@code saved}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setSaved(Boolean value) {
		put("saved", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code title}; optional. Absent values return null.
	 */
	public String getTitle() {
		return read("title", String.class);
	}

	/**
	 * Sets {@code title}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setTitle(String value) {
		put("title", value);
		return this;
	}

	/**
	 * API field {@code card}; optional. Absent values return null.
	 */
	public BankCardData getCard() {
		return read("card", BankCardData.class);
	}

	/**
	 * Sets {@code card}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setCard(BankCardData value) {
		put("card", value);
		return this;
	}

	/**
	 * API field {@code electronic_certificate}; optional. Absent values return null.
	 */
	public ElectronicCertificatePayment getElectronicCertificate() {
		return read("electronic_certificate", ElectronicCertificatePayment.class);
	}

	/**
	 * Sets {@code electronic_certificate}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setElectronicCertificate(ElectronicCertificatePayment value) {
		put("electronic_certificate", value);
		return this;
	}

	/**
	 * API field {@code articles}; optional. Absent values return null.
	 */
	public java.util.List<ElectronicCertificateApprovedPaymentArticle> getArticles() {
		return read("articles", new com.google.gson.reflect.TypeToken<java.util.List<ElectronicCertificateApprovedPaymentArticle>>() {
		}.getType());
	}

	/**
	 * Sets {@code articles}; null removes the field.
	 */
	public PaymentMethodElectronicCertificate setArticles(java.util.List<ElectronicCertificateApprovedPaymentArticle> value) {
		put("articles", value);
		return this;
	}
}
