// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Payment schema. See the pinned OpenAPI specification.
 */
public class Payment extends JsonModel {
	public Payment() {
		super();
	}

	public Payment(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_WAITING_FOR_CAPTURE = "waiting_for_capture";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_PENDING = "pending";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public Payment setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Payment setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public Payment setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code income_amount}; optional. Absent values return null.
	 */
	public MonetaryAmount getIncomeAmount() {
		return read("income_amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code income_amount}; null removes the field.
	 */
	public Payment setIncomeAmount(MonetaryAmount value) {
		put("income_amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public Payment setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code recipient}; required. Absent values return null.
	 */
	public PaymentRecipient getRecipient() {
		return read("recipient", PaymentRecipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public Payment setRecipient(PaymentRecipient value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code payment_method}; optional. Absent values return null.
	 */
	public JsonModel getPaymentMethod() {
		return read("payment_method", JsonModel.class);
	}

	/**
	 * Sets {@code payment_method}; null removes the field.
	 */
	public Payment setPaymentMethod(JsonModel value) {
		put("payment_method", value);
		return this;
	}

	/**
	 * API field {@code captured_at}; optional. Absent values return null.
	 */
	public String getCapturedAt() {
		return read("captured_at", String.class);
	}

	/**
	 * Sets {@code captured_at}; null removes the field.
	 */
	public Payment setCapturedAt(String value) {
		put("captured_at", value);
		return this;
	}

	/**
	 * Parsed {@code captured_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCapturedAtAsDateTime() {
		return readDateTime("captured_at");
	}

	/**
	 * Sets {@code captured_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Payment setCapturedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("captured_at", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public Payment setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Payment setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; optional. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public Payment setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Payment setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}

	/**
	 * API field {@code confirmation}; optional. Absent values return null.
	 */
	public JsonModel getConfirmation() {
		return read("confirmation", JsonModel.class);
	}

	/**
	 * Sets {@code confirmation}; null removes the field.
	 */
	public Payment setConfirmation(JsonModel value) {
		put("confirmation", value);
		return this;
	}

	/**
	 * API field {@code test}; required. Absent values return null.
	 */
	public Boolean getTest() {
		return read("test", Boolean.class);
	}

	/**
	 * Sets {@code test}; null removes the field.
	 */
	public Payment setTest(Boolean value) {
		put("test", value);
		return this;
	}

	/**
	 * API field {@code refunded_amount}; optional. Absent values return null.
	 */
	public MonetaryAmount getRefundedAmount() {
		return read("refunded_amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code refunded_amount}; null removes the field.
	 */
	public Payment setRefundedAmount(MonetaryAmount value) {
		put("refunded_amount", value);
		return this;
	}

	/**
	 * API field {@code paid}; required. Absent values return null.
	 */
	public Boolean getPaid() {
		return read("paid", Boolean.class);
	}

	/**
	 * Sets {@code paid}; null removes the field.
	 */
	public Payment setPaid(Boolean value) {
		put("paid", value);
		return this;
	}

	/**
	 * API field {@code refundable}; required. Absent values return null.
	 */
	public Boolean getRefundable() {
		return read("refundable", Boolean.class);
	}

	/**
	 * Sets {@code refundable}; null removes the field.
	 */
	public Payment setRefundable(Boolean value) {
		put("refundable", value);
		return this;
	}

	/**
	 * API field {@code receipt_registration}; optional. Absent values return null.
	 */
	public String getReceiptRegistration() {
		return read("receipt_registration", String.class);
	}

	/**
	 * Sets {@code receipt_registration}; null removes the field.
	 */
	public Payment setReceiptRegistration(String value) {
		put("receipt_registration", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public Payment setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code cancellation_details}; optional. Absent values return null.
	 */
	public PaymentCancellationDetails getCancellationDetails() {
		return read("cancellation_details", PaymentCancellationDetails.class);
	}

	/**
	 * Sets {@code cancellation_details}; null removes the field.
	 */
	public Payment setCancellationDetails(PaymentCancellationDetails value) {
		put("cancellation_details", value);
		return this;
	}

	/**
	 * API field {@code authorization_details}; optional. Absent values return null.
	 */
	public AuthorizationDetails getAuthorizationDetails() {
		return read("authorization_details", AuthorizationDetails.class);
	}

	/**
	 * Sets {@code authorization_details}; null removes the field.
	 */
	public Payment setAuthorizationDetails(AuthorizationDetails value) {
		put("authorization_details", value);
		return this;
	}

	/**
	 * API field {@code transfers}; optional. Absent values return null.
	 */
	public java.util.List<Transfer> getTransfers() {
		return read("transfers", new com.google.gson.reflect.TypeToken<java.util.List<Transfer>>() {
		}.getType());
	}

	/**
	 * Sets {@code transfers}; null removes the field.
	 */
	public Payment setTransfers(java.util.List<Transfer> value) {
		put("transfers", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public PaymentDealInfo getDeal() {
		return read("deal", PaymentDealInfo.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public Payment setDeal(PaymentDealInfo value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code merchant_customer_id}; optional. Absent values return null.
	 */
	public String getMerchantCustomerId() {
		return read("merchant_customer_id", String.class);
	}

	/**
	 * Sets {@code merchant_customer_id}; null removes the field.
	 */
	public Payment setMerchantCustomerId(String value) {
		put("merchant_customer_id", value);
		return this;
	}

	/**
	 * API field {@code invoice_details}; optional. Absent values return null.
	 */
	public PaymentInvoiceDetails getInvoiceDetails() {
		return read("invoice_details", PaymentInvoiceDetails.class);
	}

	/**
	 * Sets {@code invoice_details}; null removes the field.
	 */
	public Payment setInvoiceDetails(PaymentInvoiceDetails value) {
		put("invoice_details", value);
		return this;
	}
}
