// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentData schema. See the pinned OpenAPI specification.
 */
public class PaymentData extends JsonModel {
	public PaymentData() {
		super();
	}

	public PaymentData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public PaymentData setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code receipt}; optional. Absent values return null.
	 */
	public ReceiptData getReceipt() {
		return read("receipt", ReceiptData.class);
	}

	/**
	 * Sets {@code receipt}; null removes the field.
	 */
	public PaymentData setReceipt(ReceiptData value) {
		put("receipt", value);
		return this;
	}

	/**
	 * API field {@code recipient}; optional. Absent values return null.
	 */
	public Recipient getRecipient() {
		return read("recipient", Recipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public PaymentData setRecipient(Recipient value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code save_payment_method}; optional. Absent values return null.
	 */
	public Boolean getSavePaymentMethod() {
		return read("save_payment_method", Boolean.class);
	}

	/**
	 * Sets {@code save_payment_method}; null removes the field.
	 */
	public PaymentData setSavePaymentMethod(Boolean value) {
		put("save_payment_method", value);
		return this;
	}

	/**
	 * API field {@code capture}; optional. Absent values return null.
	 */
	public Boolean getCapture() {
		return read("capture", Boolean.class);
	}

	/**
	 * Sets {@code capture}; null removes the field.
	 */
	public PaymentData setCapture(Boolean value) {
		put("capture", value);
		return this;
	}

	/**
	 * API field {@code client_ip}; optional. Absent values return null.
	 */
	public String getClientIp() {
		return read("client_ip", String.class);
	}

	/**
	 * Sets {@code client_ip}; null removes the field.
	 */
	public PaymentData setClientIp(String value) {
		put("client_ip", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public PaymentData setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public PaymentData setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
