// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentDealInfo schema. See the pinned OpenAPI specification.
 */
public class PaymentDealInfo extends JsonModel {
	public PaymentDealInfo() {
		super();
	}

	public PaymentDealInfo(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PaymentDealInfo setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code settlements}; required. Absent values return null.
	 */
	public java.util.List<JsonModel> getSettlements() {
		return read("settlements", new com.google.gson.reflect.TypeToken<java.util.List<JsonModel>>() {
		}.getType());
	}

	/**
	 * Sets {@code settlements}; null removes the field.
	 */
	public PaymentDealInfo setSettlements(java.util.List<JsonModel> value) {
		put("settlements", value);
		return this;
	}
}
