// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodsConfirmationRedirect schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodsConfirmationRedirect extends JsonModel {
	public PaymentMethodsConfirmationRedirect() {
		super();
	}

	public PaymentMethodsConfirmationRedirect(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REDIRECT = "redirect";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QR = "qr";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodsConfirmationRedirect setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code confirmation_url}; required. Absent values return null.
	 */
	public String getConfirmationUrl() {
		return read("confirmation_url", String.class);
	}

	/**
	 * Sets {@code confirmation_url}; null removes the field.
	 */
	public PaymentMethodsConfirmationRedirect setConfirmationUrl(String value) {
		put("confirmation_url", value);
		return this;
	}

	/**
	 * API field {@code enforce}; optional. Absent values return null.
	 */
	public Boolean getEnforce() {
		return read("enforce", Boolean.class);
	}

	/**
	 * Sets {@code enforce}; null removes the field.
	 */
	public PaymentMethodsConfirmationRedirect setEnforce(Boolean value) {
		put("enforce", value);
		return this;
	}

	/**
	 * API field {@code return_url}; optional. Absent values return null.
	 */
	public String getReturnUrl() {
		return read("return_url", String.class);
	}

	/**
	 * Sets {@code return_url}; null removes the field.
	 */
	public PaymentMethodsConfirmationRedirect setReturnUrl(String value) {
		put("return_url", value);
		return this;
	}
}
