// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodSberLoan schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodSberLoan extends JsonModel {
	public PaymentMethodSberLoan() {
		super();
	}

	public PaymentMethodSberLoan(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CASH = "cash";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ALFABANK = "alfabank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_WEBMONEY = "webmoney";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_WECHAT = "wechat";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_APPLE_PAY = "apple_pay";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_GOOGLE_PAY = "google_pay";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_QIWI = "qiwi";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_INSTALLMENTS = "installments";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBERBANK = "sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_B2B_SBERBANK = "b2b_sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_TINKOFF_BANK = "tinkoff_bank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_LOAN = "sber_loan";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ELECTRONIC_CERTIFICATE = "electronic_certificate";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_BNPL = "sber_bnpl";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ALFA_PAY = "alfa_pay";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ACTIVE = "active";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_INACTIVE = "inactive";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodSberLoan setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PaymentMethodSberLoan setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code saved}; required. Absent values return null.
	 */
	public Boolean getSaved() {
		return read("saved", Boolean.class);
	}

	/**
	 * Sets {@code saved}; null removes the field.
	 */
	public PaymentMethodSberLoan setSaved(Boolean value) {
		put("saved", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public PaymentMethodSberLoan setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code title}; optional. Absent values return null.
	 */
	public String getTitle() {
		return read("title", String.class);
	}

	/**
	 * Sets {@code title}; null removes the field.
	 */
	public PaymentMethodSberLoan setTitle(String value) {
		put("title", value);
		return this;
	}

	/**
	 * API field {@code loan_option}; optional. Absent values return null.
	 */
	public String getLoanOption() {
		return read("loan_option", String.class);
	}

	/**
	 * Sets {@code loan_option}; null removes the field.
	 */
	public PaymentMethodSberLoan setLoanOption(String value) {
		put("loan_option", value);
		return this;
	}

	/**
	 * API field {@code discount_amount}; optional. Absent values return null.
	 */
	public MonetaryAmount getDiscountAmount() {
		return read("discount_amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code discount_amount}; null removes the field.
	 */
	public PaymentMethodSberLoan setDiscountAmount(MonetaryAmount value) {
		put("discount_amount", value);
		return this;
	}

	/**
	 * API field {@code suspended_until}; optional. Absent values return null.
	 */
	public String getSuspendedUntil() {
		return read("suspended_until", String.class);
	}

	/**
	 * Sets {@code suspended_until}; null removes the field.
	 */
	public PaymentMethodSberLoan setSuspendedUntil(String value) {
		put("suspended_until", value);
		return this;
	}

	/**
	 * Parsed {@code suspended_until}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSuspendedUntilAsDateTime() {
		return readDateTime("suspended_until");
	}

	/**
	 * Sets {@code suspended_until} as an ISO-8601 date-time; null removes the field.
	 */
	public PaymentMethodSberLoan setSuspendedUntilAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("suspended_until", value);
		return this;
	}
}
