// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentMethodDataElectronicCertificate schema. See the pinned OpenAPI specification.
 */
public class PaymentMethodDataElectronicCertificate extends JsonModel {
	public PaymentMethodDataElectronicCertificate() {
		super();
	}

	public PaymentMethodDataElectronicCertificate(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CASH = "cash";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBERBANK = "sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_TINKOFF_BANK = "tinkoff_bank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_B2B_SBERBANK = "b2b_sberbank";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_LOAN = "sber_loan";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ELECTRONIC_CERTIFICATE = "electronic_certificate";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBER_BNPL = "sber_bnpl";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ALFA_PAY = "alfa_pay";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentMethodDataElectronicCertificate setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code card}; optional. Absent values return null.
	 */
	public CardRequestDataWithCsc getCard() {
		return read("card", CardRequestDataWithCsc.class);
	}

	/**
	 * Sets {@code card}; null removes the field.
	 */
	public PaymentMethodDataElectronicCertificate setCard(CardRequestDataWithCsc value) {
		put("card", value);
		return this;
	}

	/**
	 * API field {@code electronic_certificate}; optional. Absent values return null.
	 */
	public ElectronicCertificatePaymentData getElectronicCertificate() {
		return read("electronic_certificate", ElectronicCertificatePaymentData.class);
	}

	/**
	 * Sets {@code electronic_certificate}; null removes the field.
	 */
	public PaymentMethodDataElectronicCertificate setElectronicCertificate(ElectronicCertificatePaymentData value) {
		put("electronic_certificate", value);
		return this;
	}

	/**
	 * API field {@code articles}; optional. Absent values return null.
	 */
	public java.util.List<ElectronicCertificateArticle> getArticles() {
		return read("articles", new com.google.gson.reflect.TypeToken<java.util.List<ElectronicCertificateArticle>>() {
		}.getType());
	}

	/**
	 * Sets {@code articles}; null removes the field.
	 */
	public PaymentMethodDataElectronicCertificate setArticles(java.util.List<ElectronicCertificateArticle> value) {
		put("articles", value);
		return this;
	}
}
