// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PaymentOverviewStatementEmailDeliveryMethod schema. See the pinned OpenAPI specification.
 */
public class PaymentOverviewStatementEmailDeliveryMethod extends JsonModel {
	public PaymentOverviewStatementEmailDeliveryMethod() {
		super();
	}

	public PaymentOverviewStatementEmailDeliveryMethod(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_EMAIL = "email";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PaymentOverviewStatementEmailDeliveryMethod setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code email}; required. Absent values return null.
	 */
	public String getEmail() {
		return read("email", String.class);
	}

	/**
	 * Sets {@code email}; null removes the field.
	 */
	public PaymentOverviewStatementEmailDeliveryMethod setEmail(String value) {
		put("email", value);
		return this;
	}
}
