// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutDeal schema. See the pinned OpenAPI specification.
 */
public class PayoutDeal extends JsonModel {
	public PayoutDeal() {
		super();
	}

	public PayoutDeal(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PayoutDeal setId(String value) {
		put("id", value);
		return this;
	}
}
