// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutCancellationDetails schema. See the pinned OpenAPI specification.
 */
public class PayoutCancellationDetails extends JsonModel {
	public PayoutCancellationDetails() {
		super();
	}

	public PayoutCancellationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_PAYOUT_NETWORK = "payout_network";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INSUFFICIENT_FUNDS = "insufficient_funds";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_FRAUD_SUSPECTED = "fraud_suspected";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_ONE_TIME_LIMIT_EXCEEDED = "one_time_limit_exceeded";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PERIODIC_LIMIT_EXCEEDED = "periodic_limit_exceeded";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_REJECTED_BY_PAYEE = "rejected_by_payee";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_GENERAL_DECLINE = "general_decline";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_ISSUER_UNAVAILABLE = "issuer_unavailable";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_RECIPIENT_NOT_FOUND = "recipient_not_found";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_RECIPIENT_CHECK_FAILED = "recipient_check_failed";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_IDENTIFICATION_REQUIRED = "identification_required";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_SELF_EMPLOYED_ANNUAL_LIMIT_EXCEEDED = "self_employed_annual_limit_exceeded";

	/**
	 * API field {@code party}; required. Absent values return null.
	 */
	public String getParty() {
		return read("party", String.class);
	}

	/**
	 * Sets {@code party}; null removes the field.
	 */
	public PayoutCancellationDetails setParty(String value) {
		put("party", value);
		return this;
	}

	/**
	 * API field {@code reason}; required. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public PayoutCancellationDetails setReason(String value) {
		put("reason", value);
		return this;
	}
}
