// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutToCardDestination schema. See the pinned OpenAPI specification.
 */
public class PayoutToCardDestination extends JsonModel {
	public PayoutToCardDestination() {
		super();
	}

	public PayoutToCardDestination(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PayoutToCardDestination setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code card}; optional. Absent values return null.
	 */
	public PayoutCardData getCard() {
		return read("card", PayoutCardData.class);
	}

	/**
	 * Sets {@code card}; null removes the field.
	 */
	public PayoutToCardDestination setCard(PayoutCardData value) {
		put("card", value);
		return this;
	}
}
