// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutsList schema. See the pinned OpenAPI specification.
 */
public class PayoutsList extends JsonModel {
	public PayoutsList() {
		super();
	}

	public PayoutsList(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_LIST = "list";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PayoutsList setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<Payout> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<Payout>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public PayoutsList setItems(java.util.List<Payout> value) {
		put("items", value);
		return this;
	}

	/**
	 * API field {@code next_cursor}; optional. Absent values return null.
	 */
	public String getNextCursor() {
		return read("next_cursor", String.class);
	}

	/**
	 * Sets {@code next_cursor}; null removes the field.
	 */
	public PayoutsList setNextCursor(String value) {
		put("next_cursor", value);
		return this;
	}
}
