// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutToSbpDestination schema. See the pinned OpenAPI specification.
 */
public class PayoutToSbpDestination extends JsonModel {
	public PayoutToSbpDestination() {
		super();
	}

	public PayoutToSbpDestination(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PayoutToSbpDestination setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code phone}; required. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public PayoutToSbpDestination setPhone(String value) {
		put("phone", value);
		return this;
	}

	/**
	 * API field {@code bank_id}; required. Absent values return null.
	 */
	public String getBankId() {
		return read("bank_id", String.class);
	}

	/**
	 * Sets {@code bank_id}; null removes the field.
	 */
	public PayoutToSbpDestination setBankId(String value) {
		put("bank_id", value);
		return this;
	}

	/**
	 * API field {@code sbp_operation_id}; optional. Absent values return null.
	 */
	public String getSbpOperationId() {
		return read("sbp_operation_id", String.class);
	}

	/**
	 * Sets {@code sbp_operation_id}; null removes the field.
	 */
	public PayoutToSbpDestination setSbpOperationId(String value) {
		put("sbp_operation_id", value);
		return this;
	}

	/**
	 * API field {@code recipient_checked}; required. Absent values return null.
	 */
	public Boolean getRecipientChecked() {
		return read("recipient_checked", Boolean.class);
	}

	/**
	 * Sets {@code recipient_checked}; null removes the field.
	 */
	public PayoutToSbpDestination setRecipientChecked(Boolean value) {
		put("recipient_checked", value);
		return this;
	}
}
