// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutRequest schema. See the pinned OpenAPI specification.
 */
public class PayoutRequest extends JsonModel {
	public PayoutRequest() {
		super();
	}

	public PayoutRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public PayoutRequest setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code payout_destination_data}; optional. Absent values return null.
	 */
	public JsonModel getPayoutDestinationData() {
		return read("payout_destination_data", JsonModel.class);
	}

	/**
	 * Sets {@code payout_destination_data}; null removes the field.
	 */
	public PayoutRequest setPayoutDestinationData(JsonModel value) {
		put("payout_destination_data", value);
		return this;
	}

	/**
	 * API field {@code payout_token}; optional. Absent values return null.
	 */
	public String getPayoutToken() {
		return read("payout_token", String.class);
	}

	/**
	 * Sets {@code payout_token}; null removes the field.
	 */
	public PayoutRequest setPayoutToken(String value) {
		put("payout_token", value);
		return this;
	}

	/**
	 * API field {@code payment_method_id}; optional. Absent values return null.
	 */
	public String getPaymentMethodId() {
		return read("payment_method_id", String.class);
	}

	/**
	 * Sets {@code payment_method_id}; null removes the field.
	 */
	public PayoutRequest setPaymentMethodId(String value) {
		put("payment_method_id", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public PayoutRequest setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public PayoutDealInfo getDeal() {
		return read("deal", PayoutDealInfo.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public PayoutRequest setDeal(PayoutDealInfo value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code personal_data}; optional. Absent values return null.
	 */
	public java.util.List<PayoutsPersonalData> getPersonalData() {
		return read("personal_data", new com.google.gson.reflect.TypeToken<java.util.List<PayoutsPersonalData>>() {
		}.getType());
	}

	/**
	 * Sets {@code personal_data}; null removes the field.
	 */
	public PayoutRequest setPersonalData(java.util.List<PayoutsPersonalData> value) {
		put("personal_data", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public PayoutRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
