// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutToYooMoneyDestination schema. See the pinned OpenAPI specification.
 */
public class PayoutToYooMoneyDestination extends JsonModel {
	public PayoutToYooMoneyDestination() {
		super();
	}

	public PayoutToYooMoneyDestination(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PayoutToYooMoneyDestination setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code account_number}; required. Absent values return null.
	 */
	public String getAccountNumber() {
		return read("account_number", String.class);
	}

	/**
	 * Sets {@code account_number}; null removes the field.
	 */
	public PayoutToYooMoneyDestination setAccountNumber(String value) {
		put("account_number", value);
		return this;
	}
}
