// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutToSbpDestinationData schema. See the pinned OpenAPI specification.
 */
public class PayoutToSbpDestinationData extends JsonModel {
	public PayoutToSbpDestinationData() {
		super();
	}

	public PayoutToSbpDestinationData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PayoutToSbpDestinationData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code phone}; required. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public PayoutToSbpDestinationData setPhone(String value) {
		put("phone", value);
		return this;
	}

	/**
	 * API field {@code bank_id}; required. Absent values return null.
	 */
	public String getBankId() {
		return read("bank_id", String.class);
	}

	/**
	 * Sets {@code bank_id}; null removes the field.
	 */
	public PayoutToSbpDestinationData setBankId(String value) {
		put("bank_id", value);
		return this;
	}
}
