// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Payout schema. See the pinned OpenAPI specification.
 */
public class Payout extends JsonModel {
	public Payout() {
		super();
	}

	public Payout(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public Payout setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public Payout setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Payout setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code payout_destination}; required. Absent values return null.
	 */
	public JsonModel getPayoutDestination() {
		return read("payout_destination", JsonModel.class);
	}

	/**
	 * Sets {@code payout_destination}; null removes the field.
	 */
	public Payout setPayoutDestination(JsonModel value) {
		put("payout_destination", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public Payout setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public Payout setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Payout setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code succeeded_at}; optional. Absent values return null.
	 */
	public String getSucceededAt() {
		return read("succeeded_at", String.class);
	}

	/**
	 * Sets {@code succeeded_at}; null removes the field.
	 */
	public Payout setSucceededAt(String value) {
		put("succeeded_at", value);
		return this;
	}

	/**
	 * Parsed {@code succeeded_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getSucceededAtAsDateTime() {
		return readDateTime("succeeded_at");
	}

	/**
	 * Sets {@code succeeded_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Payout setSucceededAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("succeeded_at", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public PayoutDeal getDeal() {
		return read("deal", PayoutDeal.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public Payout setDeal(PayoutDeal value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code self_employed}; optional. Absent values return null.
	 */
	public PayoutSelfEmployed getSelfEmployed() {
		return read("self_employed", PayoutSelfEmployed.class);
	}

	/**
	 * Sets {@code self_employed}; null removes the field.
	 */
	public Payout setSelfEmployed(PayoutSelfEmployed value) {
		put("self_employed", value);
		return this;
	}

	/**
	 * API field {@code receipt}; optional. Absent values return null.
	 */
	public IncomeReceipt getReceipt() {
		return read("receipt", IncomeReceipt.class);
	}

	/**
	 * Sets {@code receipt}; null removes the field.
	 */
	public Payout setReceipt(IncomeReceipt value) {
		put("receipt", value);
		return this;
	}

	/**
	 * API field {@code cancellation_details}; optional. Absent values return null.
	 */
	public PayoutCancellationDetails getCancellationDetails() {
		return read("cancellation_details", PayoutCancellationDetails.class);
	}

	/**
	 * Sets {@code cancellation_details}; null removes the field.
	 */
	public Payout setCancellationDetails(PayoutCancellationDetails value) {
		put("cancellation_details", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public Payout setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code test}; required. Absent values return null.
	 */
	public Boolean getTest() {
		return read("test", Boolean.class);
	}

	/**
	 * Sets {@code test}; null removes the field.
	 */
	public Payout setTest(Boolean value) {
		put("test", value);
		return this;
	}
}
