// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PayoutsPersonalData schema. See the pinned OpenAPI specification.
 */
public class PayoutsPersonalData extends JsonModel {
	public PayoutsPersonalData() {
		super();
	}

	public PayoutsPersonalData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PayoutsPersonalData setId(String value) {
		put("id", value);
		return this;
	}
}
