// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PersonalDataRequest schema. See the pinned OpenAPI specification.
 */
public class PersonalDataRequest extends JsonModel {
	public PersonalDataRequest() {
		super();
	}

	public PersonalDataRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYOUT_STATEMENT_RECIPIENT = "payout_statement_recipient";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP_PAYOUT_RECIPIENT = "sbp_payout_recipient";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PersonalDataRequest setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public PersonalDataRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
