// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PersonalDataCancellationDetails schema. See the pinned OpenAPI specification.
 */
public class PersonalDataCancellationDetails extends JsonModel {
	public PersonalDataCancellationDetails() {
		super();
	}

	public PersonalDataCancellationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_EXPIRED_BY_TIMEOUT = "expired_by_timeout";

	/**
	 * API field {@code party}; required. Absent values return null.
	 */
	public String getParty() {
		return read("party", String.class);
	}

	/**
	 * Sets {@code party}; null removes the field.
	 */
	public PersonalDataCancellationDetails setParty(String value) {
		put("party", value);
		return this;
	}

	/**
	 * API field {@code reason}; required. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public PersonalDataCancellationDetails setReason(String value) {
		put("reason", value);
		return this;
	}
}
