// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PersonalData schema. See the pinned OpenAPI specification.
 */
public class PersonalData extends JsonModel {
	public PersonalData() {
		super();
	}

	public PersonalData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYOUT_STATEMENT_RECIPIENT = "payout_statement_recipient";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP_PAYOUT_RECIPIENT = "sbp_payout_recipient";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_WAITING_FOR_OPERATION = "waiting_for_operation";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ACTIVE = "active";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PersonalData setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PersonalData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public PersonalData setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code cancellation_details}; optional. Absent values return null.
	 */
	public PersonalDataCancellationDetails getCancellationDetails() {
		return read("cancellation_details", PersonalDataCancellationDetails.class);
	}

	/**
	 * Sets {@code cancellation_details}; null removes the field.
	 */
	public PersonalData setCancellationDetails(PersonalDataCancellationDetails value) {
		put("cancellation_details", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public PersonalData setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public PersonalData setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; optional. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public PersonalData setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public PersonalData setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public PersonalData setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
