// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PosLinkPaymentData schema. See the pinned OpenAPI specification.
 */
public class PosLinkPaymentData extends JsonModel {
	public PosLinkPaymentData() {
		super();
	}

	public PosLinkPaymentData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PosLinkPaymentData setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; required. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public PosLinkPaymentData setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public PosLinkPaymentData setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}
}
