// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PosLinkInfo schema. See the pinned OpenAPI specification.
 */
public class PosLinkInfo extends JsonModel {
	public PosLinkInfo() {
		super();
	}

	public PosLinkInfo(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ACTIVE = "active";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_INACTIVE = "inactive";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_NSPK = "nspk";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public PosLinkInfo setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public PosLinkInfo setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PosLinkInfo setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code recipient}; required. Absent values return null.
	 */
	public Recipient getRecipient() {
		return read("recipient", Recipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public PosLinkInfo setRecipient(Recipient value) {
		put("recipient", value);
		return this;
	}

	/**
	 * API field {@code payment}; optional. Absent values return null.
	 */
	public PosLinkLastPayment getPayment() {
		return read("payment", PosLinkLastPayment.class);
	}

	/**
	 * Sets {@code payment}; null removes the field.
	 */
	public PosLinkInfo setPayment(PosLinkLastPayment value) {
		put("payment", value);
		return this;
	}
}
