// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PosLinkData schema. See the pinned OpenAPI specification.
 */
public class PosLinkData extends JsonModel {
	public PosLinkData() {
		super();
	}

	public PosLinkData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code link}; required. Absent values return null.
	 */
	public String getLink() {
		return read("link", String.class);
	}

	/**
	 * Sets {@code link}; null removes the field.
	 */
	public PosLinkData setLink(String value) {
		put("link", value);
		return this;
	}
}
