// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PostReceiptDataItem schema. See the pinned OpenAPI specification.
 */
public class PostReceiptDataItem extends JsonModel {
	public PostReceiptDataItem() {
		super();
	}

	public PostReceiptDataItem(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_PIECE = "piece";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_GRAM = "gram";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_KILOGRAM = "kilogram";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_TON = "ton";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_CENTIMETER = "centimeter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_DECIMETER = "decimeter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_METER = "meter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_SQUARE_CENTIMETER = "square_centimeter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_SQUARE_DECIMETER = "square_decimeter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_SQUARE_METER = "square_meter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_MILLILITER = "milliliter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_LITER = "liter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_CUBIC_METER = "cubic_meter";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_KILOWATT_HOUR = "kilowatt_hour";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_GIGACALORIE = "gigacalorie";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_DAY = "day";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_HOUR = "hour";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_MINUTE = "minute";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_SECOND = "second";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_KILOBYTE = "kilobyte";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_MEGABYTE = "megabyte";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_GIGABYTE = "gigabyte";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_TERABYTE = "terabyte";
	/**
	 * Documented value of {@code measure}. The API may return values added later.
	 */
	public static final String MEASURE_ANOTHER = "another";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_COMMODITY = "commodity";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_EXCISE = "excise";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_JOB = "job";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_SERVICE = "service";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_GAMBLING_BET = "gambling_bet";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_GAMBLING_PRIZE = "gambling_prize";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_LOTTERY = "lottery";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_LOTTERY_PRIZE = "lottery_prize";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_INTELLECTUAL_ACTIVITY = "intellectual_activity";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_PAYMENT = "payment";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_AGENT_COMMISSION = "agent_commission";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_PROPERTY_RIGHT = "property_right";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_NON_OPERATING_GAIN = "non_operating_gain";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_INSURANCE_PREMIUM = "insurance_premium";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_SALES_TAX = "sales_tax";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_RESORT_FEE = "resort_fee";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_COMPOSITE = "composite";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_ANOTHER = "another";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_FINE = "fine";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_TAX = "tax";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_LIEN = "lien";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_COST = "cost";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_PENSION_INSURANCE_WITHOUT_PAYOUTS = "pension_insurance_without_payouts";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_PENSION_INSURANCE_WITH_PAYOUTS = "pension_insurance_with_payouts";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_HEALTH_INSURANCE_WITHOUT_PAYOUTS = "health_insurance_without_payouts";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_HEALTH_INSURANCE_WITH_PAYOUTS = "health_insurance_with_payouts";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_HEALTH_INSURANCE = "health_insurance";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_CASINO = "casino";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_AGENT_WITHDRAWALS = "agent_withdrawals";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_NON_MARKED_EXCISE = "non_marked_excise";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_MARKED_EXCISE = "marked_excise";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_MARKED = "marked";
	/**
	 * Documented value of {@code payment_subject}. The API may return values added later.
	 */
	public static final String PAYMENT_SUBJECT_NON_MARKED = "non_marked";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_FULL_PREPAYMENT = "full_prepayment";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_PARTIAL_PREPAYMENT = "partial_prepayment";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_ADVANCE = "advance";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_FULL_PAYMENT = "full_payment";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_PARTIAL_PAYMENT = "partial_payment";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_CREDIT = "credit";
	/**
	 * Documented value of {@code payment_mode}. The API may return values added later.
	 */
	public static final String PAYMENT_MODE_CREDIT_PAYMENT = "credit_payment";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_BANKING_PAYMENT_AGENT = "banking_payment_agent";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_BANKING_PAYMENT_SUBAGENT = "banking_payment_subagent";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_PAYMENT_AGENT = "payment_agent";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_PAYMENT_SUBAGENT = "payment_subagent";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_ATTORNEY = "attorney";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_COMMISSIONER = "commissioner";
	/**
	 * Documented value of {@code agent_type}. The API may return values added later.
	 */
	public static final String AGENT_TYPE_AGENT = "agent";

	/**
	 * API field {@code description}; required. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public PostReceiptDataItem setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public PostReceiptDataItem setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code vat_code}; required. Absent values return null.
	 */
	public Long getVatCode() {
		return read("vat_code", Long.class);
	}

	/**
	 * Sets {@code vat_code}; null removes the field.
	 */
	public PostReceiptDataItem setVatCode(Long value) {
		put("vat_code", value);
		return this;
	}

	/**
	 * API field {@code quantity}; required. Absent values return null.
	 */
	public java.math.BigDecimal getQuantity() {
		return read("quantity", java.math.BigDecimal.class);
	}

	/**
	 * Sets {@code quantity}; null removes the field.
	 */
	public PostReceiptDataItem setQuantity(java.math.BigDecimal value) {
		put("quantity", value);
		return this;
	}

	/**
	 * API field {@code measure}; optional. Absent values return null.
	 */
	public String getMeasure() {
		return read("measure", String.class);
	}

	/**
	 * Sets {@code measure}; null removes the field.
	 */
	public PostReceiptDataItem setMeasure(String value) {
		put("measure", value);
		return this;
	}

	/**
	 * API field {@code mark_quantity}; optional. Absent values return null.
	 */
	public MarkQuantity getMarkQuantity() {
		return read("mark_quantity", MarkQuantity.class);
	}

	/**
	 * Sets {@code mark_quantity}; null removes the field.
	 */
	public PostReceiptDataItem setMarkQuantity(MarkQuantity value) {
		put("mark_quantity", value);
		return this;
	}

	/**
	 * API field {@code payment_subject}; optional. Absent values return null.
	 */
	public String getPaymentSubject() {
		return read("payment_subject", String.class);
	}

	/**
	 * Sets {@code payment_subject}; null removes the field.
	 */
	public PostReceiptDataItem setPaymentSubject(String value) {
		put("payment_subject", value);
		return this;
	}

	/**
	 * API field {@code payment_mode}; optional. Absent values return null.
	 */
	public String getPaymentMode() {
		return read("payment_mode", String.class);
	}

	/**
	 * Sets {@code payment_mode}; null removes the field.
	 */
	public PostReceiptDataItem setPaymentMode(String value) {
		put("payment_mode", value);
		return this;
	}

	/**
	 * API field {@code country_of_origin_code}; optional. Absent values return null.
	 */
	public String getCountryOfOriginCode() {
		return read("country_of_origin_code", String.class);
	}

	/**
	 * Sets {@code country_of_origin_code}; null removes the field.
	 */
	public PostReceiptDataItem setCountryOfOriginCode(String value) {
		put("country_of_origin_code", value);
		return this;
	}

	/**
	 * API field {@code customs_declaration_number}; optional. Absent values return null.
	 */
	public String getCustomsDeclarationNumber() {
		return read("customs_declaration_number", String.class);
	}

	/**
	 * Sets {@code customs_declaration_number}; null removes the field.
	 */
	public PostReceiptDataItem setCustomsDeclarationNumber(String value) {
		put("customs_declaration_number", value);
		return this;
	}

	/**
	 * API field {@code excise}; optional. Absent values return null.
	 */
	public String getExcise() {
		return read("excise", String.class);
	}

	/**
	 * Sets {@code excise}; null removes the field.
	 */
	public PostReceiptDataItem setExcise(String value) {
		put("excise", value);
		return this;
	}

	/**
	 * API field {@code product_code}; optional. Absent values return null.
	 */
	public String getProductCode() {
		return read("product_code", String.class);
	}

	/**
	 * Sets {@code product_code}; null removes the field.
	 */
	public PostReceiptDataItem setProductCode(String value) {
		put("product_code", value);
		return this;
	}

	/**
	 * API field {@code planned_status}; optional. Absent values return null.
	 */
	public Long getPlannedStatus() {
		return read("planned_status", Long.class);
	}

	/**
	 * Sets {@code planned_status}; null removes the field.
	 */
	public PostReceiptDataItem setPlannedStatus(Long value) {
		put("planned_status", value);
		return this;
	}

	/**
	 * API field {@code mark_code_info}; optional. Absent values return null.
	 */
	public MarkCodeInfo getMarkCodeInfo() {
		return read("mark_code_info", MarkCodeInfo.class);
	}

	/**
	 * Sets {@code mark_code_info}; null removes the field.
	 */
	public PostReceiptDataItem setMarkCodeInfo(MarkCodeInfo value) {
		put("mark_code_info", value);
		return this;
	}

	/**
	 * API field {@code mark_mode}; optional. Absent values return null.
	 */
	public String getMarkMode() {
		return read("mark_mode", String.class);
	}

	/**
	 * Sets {@code mark_mode}; null removes the field.
	 */
	public PostReceiptDataItem setMarkMode(String value) {
		put("mark_mode", value);
		return this;
	}

	/**
	 * API field {@code payment_subject_industry_details}; optional. Absent values return null.
	 */
	public java.util.List<IndustryDetails> getPaymentSubjectIndustryDetails() {
		return read("payment_subject_industry_details", new com.google.gson.reflect.TypeToken<java.util.List<IndustryDetails>>() {
		}.getType());
	}

	/**
	 * Sets {@code payment_subject_industry_details}; null removes the field.
	 */
	public PostReceiptDataItem setPaymentSubjectIndustryDetails(java.util.List<IndustryDetails> value) {
		put("payment_subject_industry_details", value);
		return this;
	}

	/**
	 * API field {@code additional_payment_subject_props}; optional. Absent values return null.
	 */
	public String getAdditionalPaymentSubjectProps() {
		return read("additional_payment_subject_props", String.class);
	}

	/**
	 * Sets {@code additional_payment_subject_props}; null removes the field.
	 */
	public PostReceiptDataItem setAdditionalPaymentSubjectProps(String value) {
		put("additional_payment_subject_props", value);
		return this;
	}

	/**
	 * API field {@code supplier}; optional. Absent values return null.
	 */
	public PostReceiptItemSupplierWithInn getSupplier() {
		return read("supplier", PostReceiptItemSupplierWithInn.class);
	}

	/**
	 * Sets {@code supplier}; null removes the field.
	 */
	public PostReceiptDataItem setSupplier(PostReceiptItemSupplierWithInn value) {
		put("supplier", value);
		return this;
	}

	/**
	 * API field {@code agent_type}; optional. Absent values return null.
	 */
	public String getAgentType() {
		return read("agent_type", String.class);
	}

	/**
	 * Sets {@code agent_type}; null removes the field.
	 */
	public PostReceiptDataItem setAgentType(String value) {
		put("agent_type", value);
		return this;
	}
}
