// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the PostReceiptData schema. See the pinned OpenAPI specification.
 */
public class PostReceiptData extends JsonModel {
	public PostReceiptData() {
		super();
	}

	public PostReceiptData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYMENT = "payment";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REFUND = "refund";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public PostReceiptData setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code payment_id}; optional. Absent values return null.
	 */
	public String getPaymentId() {
		return read("payment_id", String.class);
	}

	/**
	 * Sets {@code payment_id}; null removes the field.
	 */
	public PostReceiptData setPaymentId(String value) {
		put("payment_id", value);
		return this;
	}

	/**
	 * API field {@code refund_id}; optional. Absent values return null.
	 */
	public String getRefundId() {
		return read("refund_id", String.class);
	}

	/**
	 * Sets {@code refund_id}; null removes the field.
	 */
	public PostReceiptData setRefundId(String value) {
		put("refund_id", value);
		return this;
	}

	/**
	 * API field {@code customer}; required. Absent values return null.
	 */
	public ReceiptDataCustomer getCustomer() {
		return read("customer", ReceiptDataCustomer.class);
	}

	/**
	 * Sets {@code customer}; null removes the field.
	 */
	public PostReceiptData setCustomer(ReceiptDataCustomer value) {
		put("customer", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<PostReceiptDataItem> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<PostReceiptDataItem>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public PostReceiptData setItems(java.util.List<PostReceiptDataItem> value) {
		put("items", value);
		return this;
	}

	/**
	 * API field {@code internet}; optional. Absent values return null.
	 */
	public Boolean getInternet() {
		return read("internet", Boolean.class);
	}

	/**
	 * Sets {@code internet}; null removes the field.
	 */
	public PostReceiptData setInternet(Boolean value) {
		put("internet", value);
		return this;
	}

	/**
	 * API field {@code send}; required. Absent values return null.
	 */
	public Boolean getSend() {
		return read("send", Boolean.class);
	}

	/**
	 * Sets {@code send}; null removes the field.
	 */
	public PostReceiptData setSend(Boolean value) {
		put("send", value);
		return this;
	}

	/**
	 * API field {@code tax_system_code}; optional. Absent values return null.
	 */
	public Long getTaxSystemCode() {
		return read("tax_system_code", Long.class);
	}

	/**
	 * Sets {@code tax_system_code}; null removes the field.
	 */
	public PostReceiptData setTaxSystemCode(Long value) {
		put("tax_system_code", value);
		return this;
	}

	/**
	 * API field {@code timezone}; optional. Absent values return null.
	 */
	public Long getTimezone() {
		return read("timezone", Long.class);
	}

	/**
	 * Sets {@code timezone}; null removes the field.
	 */
	public PostReceiptData setTimezone(Long value) {
		put("timezone", value);
		return this;
	}

	/**
	 * API field {@code additional_user_props}; optional. Absent values return null.
	 */
	public ReceiptAdditionalUserProps getAdditionalUserProps() {
		return read("additional_user_props", ReceiptAdditionalUserProps.class);
	}

	/**
	 * Sets {@code additional_user_props}; null removes the field.
	 */
	public PostReceiptData setAdditionalUserProps(ReceiptAdditionalUserProps value) {
		put("additional_user_props", value);
		return this;
	}

	/**
	 * API field {@code receipt_industry_details}; optional. Absent values return null.
	 */
	public java.util.List<IndustryDetails> getReceiptIndustryDetails() {
		return read("receipt_industry_details", new com.google.gson.reflect.TypeToken<java.util.List<IndustryDetails>>() {
		}.getType());
	}

	/**
	 * Sets {@code receipt_industry_details}; null removes the field.
	 */
	public PostReceiptData setReceiptIndustryDetails(java.util.List<IndustryDetails> value) {
		put("receipt_industry_details", value);
		return this;
	}

	/**
	 * API field {@code receipt_operational_details}; optional. Absent values return null.
	 */
	public OperationalDetails getReceiptOperationalDetails() {
		return read("receipt_operational_details", OperationalDetails.class);
	}

	/**
	 * Sets {@code receipt_operational_details}; null removes the field.
	 */
	public PostReceiptData setReceiptOperationalDetails(OperationalDetails value) {
		put("receipt_operational_details", value);
		return this;
	}

	/**
	 * API field {@code settlements}; required. Absent values return null.
	 */
	public java.util.List<Settlement> getSettlements() {
		return read("settlements", new com.google.gson.reflect.TypeToken<java.util.List<Settlement>>() {
		}.getType());
	}

	/**
	 * Sets {@code settlements}; null removes the field.
	 */
	public PostReceiptData setSettlements(java.util.List<Settlement> value) {
		put("settlements", value);
		return this;
	}

	/**
	 * API field {@code on_behalf_of}; optional. Absent values return null.
	 */
	public String getOnBehalfOf() {
		return read("on_behalf_of", String.class);
	}

	/**
	 * Sets {@code on_behalf_of}; null removes the field.
	 */
	public PostReceiptData setOnBehalfOf(String value) {
		put("on_behalf_of", value);
		return this;
	}
}
