// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiptItemSupplier schema. See the pinned OpenAPI specification.
 */
public class ReceiptItemSupplier extends JsonModel {
	public ReceiptItemSupplier() {
		super();
	}

	public ReceiptItemSupplier(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code name}; optional. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public ReceiptItemSupplier setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code phone}; optional. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public ReceiptItemSupplier setPhone(String value) {
		put("phone", value);
		return this;
	}
}
