// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiverMobileBalance schema. See the pinned OpenAPI specification.
 */
public class ReceiverMobileBalance extends JsonModel {
	public ReceiverMobileBalance() {
		super();
	}

	public ReceiverMobileBalance(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_DIGITAL_WALLET = "digital_wallet";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_ACCOUNT = "bank_account";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ReceiverMobileBalance setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code phone}; required. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public ReceiverMobileBalance setPhone(String value) {
		put("phone", value);
		return this;
	}
}
