// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiptAdditionalUserProps schema. See the pinned OpenAPI specification.
 */
public class ReceiptAdditionalUserProps extends JsonModel {
	public ReceiptAdditionalUserProps() {
		super();
	}

	public ReceiptAdditionalUserProps(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code name}; required. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public ReceiptAdditionalUserProps setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code value}; required. Absent values return null.
	 */
	public String getValue() {
		return read("value", String.class);
	}

	/**
	 * Sets {@code value}; null removes the field.
	 */
	public ReceiptAdditionalUserProps setValue(String value) {
		put("value", value);
		return this;
	}
}
