// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiptData schema. See the pinned OpenAPI specification.
 */
public class ReceiptData extends JsonModel {
	public ReceiptData() {
		super();
	}

	public ReceiptData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code customer}; optional. Absent values return null.
	 */
	public ReceiptDataCustomer getCustomer() {
		return read("customer", ReceiptDataCustomer.class);
	}

	/**
	 * Sets {@code customer}; null removes the field.
	 */
	public ReceiptData setCustomer(ReceiptDataCustomer value) {
		put("customer", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<ReceiptDataItem> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<ReceiptDataItem>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public ReceiptData setItems(java.util.List<ReceiptDataItem> value) {
		put("items", value);
		return this;
	}

	/**
	 * API field {@code internet}; optional. Absent values return null.
	 */
	public Boolean getInternet() {
		return read("internet", Boolean.class);
	}

	/**
	 * Sets {@code internet}; null removes the field.
	 */
	public ReceiptData setInternet(Boolean value) {
		put("internet", value);
		return this;
	}

	/**
	 * API field {@code tax_system_code}; optional. Absent values return null.
	 */
	public Long getTaxSystemCode() {
		return read("tax_system_code", Long.class);
	}

	/**
	 * Sets {@code tax_system_code}; null removes the field.
	 */
	public ReceiptData setTaxSystemCode(Long value) {
		put("tax_system_code", value);
		return this;
	}

	/**
	 * API field {@code timezone}; optional. Absent values return null.
	 */
	public Long getTimezone() {
		return read("timezone", Long.class);
	}

	/**
	 * Sets {@code timezone}; null removes the field.
	 */
	public ReceiptData setTimezone(Long value) {
		put("timezone", value);
		return this;
	}

	/**
	 * API field {@code receipt_industry_details}; optional. Absent values return null.
	 */
	public java.util.List<IndustryDetails> getReceiptIndustryDetails() {
		return read("receipt_industry_details", new com.google.gson.reflect.TypeToken<java.util.List<IndustryDetails>>() {
		}.getType());
	}

	/**
	 * Sets {@code receipt_industry_details}; null removes the field.
	 */
	public ReceiptData setReceiptIndustryDetails(java.util.List<IndustryDetails> value) {
		put("receipt_industry_details", value);
		return this;
	}

	/**
	 * API field {@code receipt_operational_details}; optional. Absent values return null.
	 */
	public OperationalDetails getReceiptOperationalDetails() {
		return read("receipt_operational_details", OperationalDetails.class);
	}

	/**
	 * Sets {@code receipt_operational_details}; null removes the field.
	 */
	public ReceiptData setReceiptOperationalDetails(OperationalDetails value) {
		put("receipt_operational_details", value);
		return this;
	}
}
