// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiptItemSupplierWithInn schema. See the pinned OpenAPI specification.
 */
public class ReceiptItemSupplierWithInn extends JsonModel {
	public ReceiptItemSupplierWithInn() {
		super();
	}

	public ReceiptItemSupplierWithInn(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code name}; optional. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public ReceiptItemSupplierWithInn setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code phone}; optional. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public ReceiptItemSupplierWithInn setPhone(String value) {
		put("phone", value);
		return this;
	}

	/**
	 * API field {@code inn}; optional. Absent values return null.
	 */
	public String getInn() {
		return read("inn", String.class);
	}

	/**
	 * Sets {@code inn}; null removes the field.
	 */
	public ReceiptItemSupplierWithInn setInn(String value) {
		put("inn", value);
		return this;
	}
}
