// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiptDataCustomer schema. See the pinned OpenAPI specification.
 */
public class ReceiptDataCustomer extends JsonModel {
	public ReceiptDataCustomer() {
		super();
	}

	public ReceiptDataCustomer(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code full_name}; optional. Absent values return null.
	 */
	public String getFullName() {
		return read("full_name", String.class);
	}

	/**
	 * Sets {@code full_name}; null removes the field.
	 */
	public ReceiptDataCustomer setFullName(String value) {
		put("full_name", value);
		return this;
	}

	/**
	 * API field {@code inn}; optional. Absent values return null.
	 */
	public String getInn() {
		return read("inn", String.class);
	}

	/**
	 * Sets {@code inn}; null removes the field.
	 */
	public ReceiptDataCustomer setInn(String value) {
		put("inn", value);
		return this;
	}

	/**
	 * API field {@code email}; optional. Absent values return null.
	 */
	public String getEmail() {
		return read("email", String.class);
	}

	/**
	 * Sets {@code email}; null removes the field.
	 */
	public ReceiptDataCustomer setEmail(String value) {
		put("email", value);
		return this;
	}

	/**
	 * API field {@code phone}; optional. Absent values return null.
	 */
	public String getPhone() {
		return read("phone", String.class);
	}

	/**
	 * Sets {@code phone}; null removes the field.
	 */
	public ReceiptDataCustomer setPhone(String value) {
		put("phone", value);
		return this;
	}
}
