// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Receipt schema. See the pinned OpenAPI specification.
 */
public class Receipt extends JsonModel {
	public Receipt() {
		super();
	}

	public Receipt(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYMENT = "payment";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_REFUND = "refund";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public Receipt setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public Receipt setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code payment_id}; optional. Absent values return null.
	 */
	public String getPaymentId() {
		return read("payment_id", String.class);
	}

	/**
	 * Sets {@code payment_id}; null removes the field.
	 */
	public Receipt setPaymentId(String value) {
		put("payment_id", value);
		return this;
	}

	/**
	 * API field {@code refund_id}; optional. Absent values return null.
	 */
	public String getRefundId() {
		return read("refund_id", String.class);
	}

	/**
	 * Sets {@code refund_id}; null removes the field.
	 */
	public Receipt setRefundId(String value) {
		put("refund_id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Receipt setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code fiscal_document_number}; optional. Absent values return null.
	 */
	public String getFiscalDocumentNumber() {
		return read("fiscal_document_number", String.class);
	}

	/**
	 * Sets {@code fiscal_document_number}; null removes the field.
	 */
	public Receipt setFiscalDocumentNumber(String value) {
		put("fiscal_document_number", value);
		return this;
	}

	/**
	 * API field {@code fiscal_storage_number}; optional. Absent values return null.
	 */
	public String getFiscalStorageNumber() {
		return read("fiscal_storage_number", String.class);
	}

	/**
	 * Sets {@code fiscal_storage_number}; null removes the field.
	 */
	public Receipt setFiscalStorageNumber(String value) {
		put("fiscal_storage_number", value);
		return this;
	}

	/**
	 * API field {@code fiscal_attribute}; optional. Absent values return null.
	 */
	public String getFiscalAttribute() {
		return read("fiscal_attribute", String.class);
	}

	/**
	 * Sets {@code fiscal_attribute}; null removes the field.
	 */
	public Receipt setFiscalAttribute(String value) {
		put("fiscal_attribute", value);
		return this;
	}

	/**
	 * API field {@code registered_at}; optional. Absent values return null.
	 */
	public String getRegisteredAt() {
		return read("registered_at", String.class);
	}

	/**
	 * Sets {@code registered_at}; null removes the field.
	 */
	public Receipt setRegisteredAt(String value) {
		put("registered_at", value);
		return this;
	}

	/**
	 * Parsed {@code registered_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getRegisteredAtAsDateTime() {
		return readDateTime("registered_at");
	}

	/**
	 * Sets {@code registered_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Receipt setRegisteredAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("registered_at", value);
		return this;
	}

	/**
	 * API field {@code fiscal_provider_id}; optional. Absent values return null.
	 */
	public String getFiscalProviderId() {
		return read("fiscal_provider_id", String.class);
	}

	/**
	 * Sets {@code fiscal_provider_id}; null removes the field.
	 */
	public Receipt setFiscalProviderId(String value) {
		put("fiscal_provider_id", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<ReceiptItem> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<ReceiptItem>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public Receipt setItems(java.util.List<ReceiptItem> value) {
		put("items", value);
		return this;
	}

	/**
	 * API field {@code internet}; optional. Absent values return null.
	 */
	public Boolean getInternet() {
		return read("internet", Boolean.class);
	}

	/**
	 * Sets {@code internet}; null removes the field.
	 */
	public Receipt setInternet(Boolean value) {
		put("internet", value);
		return this;
	}

	/**
	 * API field {@code settlements}; optional. Absent values return null.
	 */
	public java.util.List<Settlement> getSettlements() {
		return read("settlements", new com.google.gson.reflect.TypeToken<java.util.List<Settlement>>() {
		}.getType());
	}

	/**
	 * Sets {@code settlements}; null removes the field.
	 */
	public Receipt setSettlements(java.util.List<Settlement> value) {
		put("settlements", value);
		return this;
	}

	/**
	 * API field {@code on_behalf_of}; optional. Absent values return null.
	 */
	public String getOnBehalfOf() {
		return read("on_behalf_of", String.class);
	}

	/**
	 * Sets {@code on_behalf_of}; null removes the field.
	 */
	public Receipt setOnBehalfOf(String value) {
		put("on_behalf_of", value);
		return this;
	}

	/**
	 * API field {@code tax_system_code}; optional. Absent values return null.
	 */
	public Long getTaxSystemCode() {
		return read("tax_system_code", Long.class);
	}

	/**
	 * Sets {@code tax_system_code}; null removes the field.
	 */
	public Receipt setTaxSystemCode(Long value) {
		put("tax_system_code", value);
		return this;
	}

	/**
	 * API field {@code timezone}; optional. Absent values return null.
	 */
	public Long getTimezone() {
		return read("timezone", Long.class);
	}

	/**
	 * Sets {@code timezone}; null removes the field.
	 */
	public Receipt setTimezone(Long value) {
		put("timezone", value);
		return this;
	}

	/**
	 * API field {@code receipt_industry_details}; optional. Absent values return null.
	 */
	public java.util.List<IndustryDetails> getReceiptIndustryDetails() {
		return read("receipt_industry_details", new com.google.gson.reflect.TypeToken<java.util.List<IndustryDetails>>() {
		}.getType());
	}

	/**
	 * Sets {@code receipt_industry_details}; null removes the field.
	 */
	public Receipt setReceiptIndustryDetails(java.util.List<IndustryDetails> value) {
		put("receipt_industry_details", value);
		return this;
	}

	/**
	 * API field {@code receipt_operational_details}; optional. Absent values return null.
	 */
	public OperationalDetails getReceiptOperationalDetails() {
		return read("receipt_operational_details", OperationalDetails.class);
	}

	/**
	 * Sets {@code receipt_operational_details}; null removes the field.
	 */
	public Receipt setReceiptOperationalDetails(OperationalDetails value) {
		put("receipt_operational_details", value);
		return this;
	}
}
