// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ReceiverDigitalWallet schema. See the pinned OpenAPI specification.
 */
public class ReceiverDigitalWallet extends JsonModel {
	public ReceiverDigitalWallet() {
		super();
	}

	public ReceiverDigitalWallet(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_MOBILE_BALANCE = "mobile_balance";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_DIGITAL_WALLET = "digital_wallet";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_ACCOUNT = "bank_account";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public ReceiverDigitalWallet setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code account_number}; required. Absent values return null.
	 */
	public String getAccountNumber() {
		return read("account_number", String.class);
	}

	/**
	 * Sets {@code account_number}; null removes the field.
	 */
	public ReceiverDigitalWallet setAccountNumber(String value) {
		put("account_number", value);
		return this;
	}
}
