// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RecipientPosLinkRequest schema. See the pinned OpenAPI specification.
 */
public class RecipientPosLinkRequest extends JsonModel {
	public RecipientPosLinkRequest() {
		super();
	}

	public RecipientPosLinkRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code recipient}; required. Absent values return null.
	 */
	public Recipient getRecipient() {
		return read("recipient", Recipient.class);
	}

	/**
	 * Sets {@code recipient}; null removes the field.
	 */
	public RecipientPosLinkRequest setRecipient(Recipient value) {
		put("recipient", value);
		return this;
	}
}
