// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Recipient schema. See the pinned OpenAPI specification.
 */
public class Recipient extends JsonModel {
	public Recipient() {
		super();
	}

	public Recipient(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code gateway_id}; required. Absent values return null.
	 */
	public String getGatewayId() {
		return read("gateway_id", String.class);
	}

	/**
	 * Sets {@code gateway_id}; null removes the field.
	 */
	public Recipient setGatewayId(String value) {
		put("gateway_id", value);
		return this;
	}
}
