// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundDealInfo schema. See the pinned OpenAPI specification.
 */
public class RefundDealInfo extends JsonModel {
	public RefundDealInfo() {
		super();
	}

	public RefundDealInfo(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public RefundDealInfo setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code refund_settlements}; required. Absent values return null.
	 */
	public java.util.List<JsonModel> getRefundSettlements() {
		return read("refund_settlements", new com.google.gson.reflect.TypeToken<java.util.List<JsonModel>>() {
		}.getType());
	}

	/**
	 * Sets {@code refund_settlements}; null removes the field.
	 */
	public RefundDealInfo setRefundSettlements(java.util.List<JsonModel> value) {
		put("refund_settlements", value);
		return this;
	}
}
