// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundCancellationDetails schema. See the pinned OpenAPI specification.
 */
public class RefundCancellationDetails extends JsonModel {
	public RefundCancellationDetails() {
		super();
	}

	public RefundCancellationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_YOO_MONEY = "yoo_money";
	/**
	 * Documented value of {@code party}. The API may return values added later.
	 */
	public static final String PARTY_REFUND_NETWORK = "refund_network";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_YOO_MONEY_ACCOUNT_CLOSED = "yoo_money_account_closed";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_INSUFFICIENT_FUNDS = "insufficient_funds";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_GENERAL_DECLINE = "general_decline";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_REJECTED_BY_PAYEE = "rejected_by_payee";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_REJECTED_BY_TIMEOUT = "rejected_by_timeout";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_BASKET_ID_NOT_FOUND = "payment_basket_id_not_found";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_ARTICLE_NUMBER_NOT_FOUND = "payment_article_number_not_found";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_TRU_CODE_NOT_FOUND = "payment_tru_code_not_found";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_TOO_MANY_REFUNDING_ARTICLES = "too_many_refunding_articles";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_SOME_ARTICLES_ALREADY_REFUNDED = "some_articles_already_refunded";
	/**
	 * Documented value of {@code reason}. The API may return values added later.
	 */
	public static final String REASON_PAYMENT_EXPIRED = "payment_expired";

	/**
	 * API field {@code party}; required. Absent values return null.
	 */
	public String getParty() {
		return read("party", String.class);
	}

	/**
	 * Sets {@code party}; null removes the field.
	 */
	public RefundCancellationDetails setParty(String value) {
		put("party", value);
		return this;
	}

	/**
	 * API field {@code reason}; required. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public RefundCancellationDetails setReason(String value) {
		put("reason", value);
		return this;
	}
}
