// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundAuthorizationDetails schema. See the pinned OpenAPI specification.
 */
public class RefundAuthorizationDetails extends JsonModel {
	public RefundAuthorizationDetails() {
		super();
	}

	public RefundAuthorizationDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code rrn}; optional. Absent values return null.
	 */
	public String getRrn() {
		return read("rrn", String.class);
	}

	/**
	 * Sets {@code rrn}; null removes the field.
	 */
	public RefundAuthorizationDetails setRrn(String value) {
		put("rrn", value);
		return this;
	}
}
