// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundSourcesDataPlatformFeeAmount schema. See the pinned OpenAPI specification.
 */
public class RefundSourcesDataPlatformFeeAmount extends JsonModel {
	public RefundSourcesDataPlatformFeeAmount() {
		super();
	}

	public RefundSourcesDataPlatformFeeAmount(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_RUB = "RUB";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_EUR = "EUR";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_USD = "USD";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_KZT = "KZT";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_BYN = "BYN";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_UAH = "UAH";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_UZS = "UZS";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_TRY = "TRY";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_INR = "INR";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_MDL = "MDL";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_AZN = "AZN";
	/**
	 * Documented value of {@code currency}. The API may return values added later.
	 */
	public static final String CURRENCY_AMD = "AMD";

	/**
	 * API field {@code value}; required. Absent values return null.
	 */
	public String getValue() {
		return read("value", String.class);
	}

	/**
	 * Sets {@code value}; null removes the field.
	 */
	public RefundSourcesDataPlatformFeeAmount setValue(String value) {
		put("value", value);
		return this;
	}

	/**
	 * Exact decimal {@code value}.
	 */
	public java.math.BigDecimal getValueAsDecimal() {
		return readDecimal("value");
	}

	/**
	 * Sets {@code value} from an exact decimal without exponent notation.
	 */
	public RefundSourcesDataPlatformFeeAmount setValueAsDecimal(java.math.BigDecimal value) {
		putDecimal("value", value);
		return this;
	}

	/**
	 * Creates an amount, for example {@code of(new BigDecimal("100.00"), "RUB")}.
	 */
	public static RefundSourcesDataPlatformFeeAmount of(java.math.BigDecimal value, String currency) {
		return new RefundSourcesDataPlatformFeeAmount().setValueAsDecimal(java.util.Objects.requireNonNull(value, "value"))
			.setCurrency(java.util.Objects.requireNonNull(currency, "currency"));
	}

	/**
	 * API field {@code currency}; required. Absent values return null.
	 */
	public String getCurrency() {
		return read("currency", String.class);
	}

	/**
	 * Sets {@code currency}; null removes the field.
	 */
	public RefundSourcesDataPlatformFeeAmount setCurrency(String value) {
		put("currency", value);
		return this;
	}
}
