// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundDealData schema. See the pinned OpenAPI specification.
 */
public class RefundDealData extends JsonModel {
	public RefundDealData() {
		super();
	}

	public RefundDealData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code refund_settlements}; required. Absent values return null.
	 */
	public java.util.List<JsonModel> getRefundSettlements() {
		return read("refund_settlements", new com.google.gson.reflect.TypeToken<java.util.List<JsonModel>>() {
		}.getType());
	}

	/**
	 * Sets {@code refund_settlements}; null removes the field.
	 */
	public RefundDealData setRefundSettlements(java.util.List<JsonModel> value) {
		put("refund_settlements", value);
		return this;
	}
}
