// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundRequest schema. See the pinned OpenAPI specification.
 */
public class RefundRequest extends JsonModel {
	public RefundRequest() {
		super();
	}

	public RefundRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code payment_id}; required. Absent values return null.
	 */
	public String getPaymentId() {
		return read("payment_id", String.class);
	}

	/**
	 * Sets {@code payment_id}; null removes the field.
	 */
	public RefundRequest setPaymentId(String value) {
		put("payment_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public RefundRequest setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public RefundRequest setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code receipt}; optional. Absent values return null.
	 */
	public ReceiptData getReceipt() {
		return read("receipt", ReceiptData.class);
	}

	/**
	 * Sets {@code receipt}; null removes the field.
	 */
	public RefundRequest setReceipt(ReceiptData value) {
		put("receipt", value);
		return this;
	}

	/**
	 * API field {@code sources}; optional. Absent values return null.
	 */
	public java.util.List<RefundSourcesData> getSources() {
		return read("sources", new com.google.gson.reflect.TypeToken<java.util.List<RefundSourcesData>>() {
		}.getType());
	}

	/**
	 * Sets {@code sources}; null removes the field.
	 */
	public RefundRequest setSources(java.util.List<RefundSourcesData> value) {
		put("sources", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public RefundDealData getDeal() {
		return read("deal", RefundDealData.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public RefundRequest setDeal(RefundDealData value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code refund_method_data}; optional. Absent values return null.
	 */
	public JsonModel getRefundMethodData() {
		return read("refund_method_data", JsonModel.class);
	}

	/**
	 * Sets {@code refund_method_data}; null removes the field.
	 */
	public RefundRequest setRefundMethodData(JsonModel value) {
		put("refund_method_data", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public RefundRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
