// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RefundSourcesData schema. See the pinned OpenAPI specification.
 */
public class RefundSourcesData extends JsonModel {
	public RefundSourcesData() {
		super();
	}

	public RefundSourcesData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public RefundSourcesData setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public RefundSourcesDataAmount getAmount() {
		return read("amount", RefundSourcesDataAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public RefundSourcesData setAmount(RefundSourcesDataAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code platform_fee_amount}; optional. Absent values return null.
	 */
	public RefundSourcesDataPlatformFeeAmount getPlatformFeeAmount() {
		return read("platform_fee_amount", RefundSourcesDataPlatformFeeAmount.class);
	}

	/**
	 * Sets {@code platform_fee_amount}; null removes the field.
	 */
	public RefundSourcesData setPlatformFeeAmount(RefundSourcesDataPlatformFeeAmount value) {
		put("platform_fee_amount", value);
		return this;
	}
}
