// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Refund schema. See the pinned OpenAPI specification.
 */
public class Refund extends JsonModel {
	public Refund() {
		super();
	}

	public Refund(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_PENDING = "pending";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code receipt_registration}. The API may return values added later.
	 */
	public static final String RECEIPT_REGISTRATION_CANCELED = "canceled";

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public Refund setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code payment_id}; required. Absent values return null.
	 */
	public String getPaymentId() {
		return read("payment_id", String.class);
	}

	/**
	 * Sets {@code payment_id}; null removes the field.
	 */
	public Refund setPaymentId(String value) {
		put("payment_id", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Refund setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code cancellation_details}; optional. Absent values return null.
	 */
	public RefundCancellationDetails getCancellationDetails() {
		return read("cancellation_details", RefundCancellationDetails.class);
	}

	/**
	 * Sets {@code cancellation_details}; null removes the field.
	 */
	public Refund setCancellationDetails(RefundCancellationDetails value) {
		put("cancellation_details", value);
		return this;
	}

	/**
	 * API field {@code receipt_registration}; optional. Absent values return null.
	 */
	public String getReceiptRegistration() {
		return read("receipt_registration", String.class);
	}

	/**
	 * Sets {@code receipt_registration}; null removes the field.
	 */
	public Refund setReceiptRegistration(String value) {
		put("receipt_registration", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public Refund setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public Refund setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public Refund setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public Refund setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code sources}; optional. Absent values return null.
	 */
	public java.util.List<RefundSourcesData> getSources() {
		return read("sources", new com.google.gson.reflect.TypeToken<java.util.List<RefundSourcesData>>() {
		}.getType());
	}

	/**
	 * Sets {@code sources}; null removes the field.
	 */
	public Refund setSources(java.util.List<RefundSourcesData> value) {
		put("sources", value);
		return this;
	}

	/**
	 * API field {@code deal}; optional. Absent values return null.
	 */
	public RefundDealInfo getDeal() {
		return read("deal", RefundDealInfo.class);
	}

	/**
	 * Sets {@code deal}; null removes the field.
	 */
	public Refund setDeal(RefundDealInfo value) {
		put("deal", value);
		return this;
	}

	/**
	 * API field {@code refund_method}; optional. Absent values return null.
	 */
	public JsonModel getRefundMethod() {
		return read("refund_method", JsonModel.class);
	}

	/**
	 * Sets {@code refund_method}; null removes the field.
	 */
	public Refund setRefundMethod(JsonModel value) {
		put("refund_method", value);
		return this;
	}

	/**
	 * API field {@code refund_authorization_details}; optional. Absent values return null.
	 */
	public RefundAuthorizationDetails getRefundAuthorizationDetails() {
		return read("refund_authorization_details", RefundAuthorizationDetails.class);
	}

	/**
	 * Sets {@code refund_authorization_details}; null removes the field.
	 */
	public Refund setRefundAuthorizationDetails(RefundAuthorizationDetails value) {
		put("refund_authorization_details", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public Refund setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
