// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the RuleViolationError schema. See the pinned OpenAPI specification.
 */
public class RuleViolationError extends JsonModel {
	public RuleViolationError() {
		super();
	}

	public RuleViolationError(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ERROR = "error";
	/**
	 * Documented value of {@code code}. The API may return values added later.
	 */
	public static final String CODE_REFUSAL = "refusal";

	/**
	 * API field {@code type}; optional. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public RuleViolationError setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; optional. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public RuleViolationError setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public RuleViolationError setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code parameter}; optional. Absent values return null.
	 */
	public String getParameter() {
		return read("parameter", String.class);
	}

	/**
	 * Sets {@code parameter}; null removes the field.
	 */
	public RuleViolationError setParameter(String value) {
		put("parameter", value);
		return this;
	}

	/**
	 * API field {@code retry_after}; optional. Absent values return null.
	 */
	public Long getRetryAfter() {
		return read("retry_after", Long.class);
	}

	/**
	 * Sets {@code retry_after}; null removes the field.
	 */
	public RuleViolationError setRetryAfter(Long value) {
		put("retry_after", value);
		return this;
	}

	/**
	 * API field {@code code}; optional. Absent values return null.
	 */
	public String getCode() {
		return read("code", String.class);
	}

	/**
	 * Sets {@code code}; null removes the field.
	 */
	public RuleViolationError setCode(String value) {
		put("code", value);
		return this;
	}

	/**
	 * API field {@code reason}; optional. Absent values return null.
	 */
	public String getReason() {
		return read("reason", String.class);
	}

	/**
	 * Sets {@code reason}; null removes the field.
	 */
	public RuleViolationError setReason(String value) {
		put("reason", value);
		return this;
	}
}
