// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SafeDealRequest schema. See the pinned OpenAPI specification.
 */
public class SafeDealRequest extends JsonModel {
	public SafeDealRequest() {
		super();
	}

	public SafeDealRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SAFE_DEAL = "safe_deal";
	/**
	 * Documented value of {@code fee_moment}. The API may return values added later.
	 */
	public static final String FEE_MOMENT_PAYMENT_SUCCEEDED = "payment_succeeded";
	/**
	 * Documented value of {@code fee_moment}. The API may return values added later.
	 */
	public static final String FEE_MOMENT_DEAL_CLOSED = "deal_closed";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SafeDealRequest setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code fee_moment}; required. Absent values return null.
	 */
	public String getFeeMoment() {
		return read("fee_moment", String.class);
	}

	/**
	 * Sets {@code fee_moment}; null removes the field.
	 */
	public SafeDealRequest setFeeMoment(String value) {
		put("fee_moment", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SafeDealRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public SafeDealRequest setDescription(String value) {
		put("description", value);
		return this;
	}
}
