// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SafeDeal schema. See the pinned OpenAPI specification.
 */
public class SafeDeal extends JsonModel {
	public SafeDeal() {
		super();
	}

	public SafeDeal(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SAFE_DEAL = "safe_deal";
	/**
	 * Documented value of {@code fee_moment}. The API may return values added later.
	 */
	public static final String FEE_MOMENT_PAYMENT_SUCCEEDED = "payment_succeeded";
	/**
	 * Documented value of {@code fee_moment}. The API may return values added later.
	 */
	public static final String FEE_MOMENT_DEAL_CLOSED = "deal_closed";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_OPENED = "opened";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CLOSED = "closed";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SafeDeal setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public SafeDeal setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code fee_moment}; required. Absent values return null.
	 */
	public String getFeeMoment() {
		return read("fee_moment", String.class);
	}

	/**
	 * Sets {@code fee_moment}; null removes the field.
	 */
	public SafeDeal setFeeMoment(String value) {
		put("fee_moment", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public SafeDeal setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code balance}; required. Absent values return null.
	 */
	public MonetaryAmount getBalance() {
		return read("balance", MonetaryAmount.class);
	}

	/**
	 * Sets {@code balance}; null removes the field.
	 */
	public SafeDeal setBalance(MonetaryAmount value) {
		put("balance", value);
		return this;
	}

	/**
	 * API field {@code payout_balance}; required. Absent values return null.
	 */
	public MonetaryAmount getPayoutBalance() {
		return read("payout_balance", MonetaryAmount.class);
	}

	/**
	 * Sets {@code payout_balance}; null removes the field.
	 */
	public SafeDeal setPayoutBalance(MonetaryAmount value) {
		put("payout_balance", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public SafeDeal setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code created_at}; required. Absent values return null.
	 */
	public String getCreatedAt() {
		return read("created_at", String.class);
	}

	/**
	 * Sets {@code created_at}; null removes the field.
	 */
	public SafeDeal setCreatedAt(String value) {
		put("created_at", value);
		return this;
	}

	/**
	 * Parsed {@code created_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtAsDateTime() {
		return readDateTime("created_at");
	}

	/**
	 * Sets {@code created_at} as an ISO-8601 date-time; null removes the field.
	 */
	public SafeDeal setCreatedAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at", value);
		return this;
	}

	/**
	 * API field {@code expires_at}; required. Absent values return null.
	 */
	public String getExpiresAt() {
		return read("expires_at", String.class);
	}

	/**
	 * Sets {@code expires_at}; null removes the field.
	 */
	public SafeDeal setExpiresAt(String value) {
		put("expires_at", value);
		return this;
	}

	/**
	 * Parsed {@code expires_at}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getExpiresAtAsDateTime() {
		return readDateTime("expires_at");
	}

	/**
	 * Sets {@code expires_at} as an ISO-8601 date-time; null removes the field.
	 */
	public SafeDeal setExpiresAtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("expires_at", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SafeDeal setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code test}; required. Absent values return null.
	 */
	public Boolean getTest() {
		return read("test", Boolean.class);
	}

	/**
	 * Sets {@code test}; null removes the field.
	 */
	public SafeDeal setTest(Boolean value) {
		put("test", value);
		return this;
	}
}
