// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SavePaymentMethodSbpPayerBankDetails schema. See the pinned OpenAPI specification.
 */
public class SavePaymentMethodSbpPayerBankDetails extends JsonModel {
	public SavePaymentMethodSbpPayerBankDetails() {
		super();
	}

	public SavePaymentMethodSbpPayerBankDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code bank_id}; required. Absent values return null.
	 */
	public String getBankId() {
		return read("bank_id", String.class);
	}

	/**
	 * Sets {@code bank_id}; null removes the field.
	 */
	public SavePaymentMethodSbpPayerBankDetails setBankId(String value) {
		put("bank_id", value);
		return this;
	}
}
