// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SavePaymentMethodSbp schema. See the pinned OpenAPI specification.
 */
public class SavePaymentMethodSbp extends JsonModel {
	public SavePaymentMethodSbp() {
		super();
	}

	public SavePaymentMethodSbp(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_ACTIVE = "active";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_INACTIVE = "inactive";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SavePaymentMethodSbp setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code id}; required. Absent values return null.
	 */
	public String getId() {
		return read("id", String.class);
	}

	/**
	 * Sets {@code id}; null removes the field.
	 */
	public SavePaymentMethodSbp setId(String value) {
		put("id", value);
		return this;
	}

	/**
	 * API field {@code saved}; required. Absent values return null.
	 */
	public Boolean getSaved() {
		return read("saved", Boolean.class);
	}

	/**
	 * Sets {@code saved}; null removes the field.
	 */
	public SavePaymentMethodSbp setSaved(Boolean value) {
		put("saved", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public SavePaymentMethodSbp setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code holder}; required. Absent values return null.
	 */
	public SavePaymentMethodSbpHolder getHolder() {
		return read("holder", SavePaymentMethodSbpHolder.class);
	}

	/**
	 * Sets {@code holder}; null removes the field.
	 */
	public SavePaymentMethodSbp setHolder(SavePaymentMethodSbpHolder value) {
		put("holder", value);
		return this;
	}

	/**
	 * API field {@code title}; optional. Absent values return null.
	 */
	public String getTitle() {
		return read("title", String.class);
	}

	/**
	 * Sets {@code title}; null removes the field.
	 */
	public SavePaymentMethodSbp setTitle(String value) {
		put("title", value);
		return this;
	}

	/**
	 * API field {@code confirmation}; optional. Absent values return null.
	 */
	public JsonModel getConfirmation() {
		return read("confirmation", JsonModel.class);
	}

	/**
	 * Sets {@code confirmation}; null removes the field.
	 */
	public SavePaymentMethodSbp setConfirmation(JsonModel value) {
		put("confirmation", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SavePaymentMethodSbp setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code payer_bank_details}; optional. Absent values return null.
	 */
	public SavePaymentMethodSbpPayerBankDetails getPayerBankDetails() {
		return read("payer_bank_details", SavePaymentMethodSbpPayerBankDetails.class);
	}

	/**
	 * Sets {@code payer_bank_details}; null removes the field.
	 */
	public SavePaymentMethodSbp setPayerBankDetails(SavePaymentMethodSbpPayerBankDetails value) {
		put("payer_bank_details", value);
		return this;
	}
}
