// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SavePaymentMethodBankCardHolder schema. See the pinned OpenAPI specification.
 */
public class SavePaymentMethodBankCardHolder extends JsonModel {
	public SavePaymentMethodBankCardHolder() {
		super();
	}

	public SavePaymentMethodBankCardHolder(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public SavePaymentMethodBankCardHolder setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code gateway_id}; optional. Absent values return null.
	 */
	public String getGatewayId() {
		return read("gateway_id", String.class);
	}

	/**
	 * Sets {@code gateway_id}; null removes the field.
	 */
	public SavePaymentMethodBankCardHolder setGatewayId(String value) {
		put("gateway_id", value);
		return this;
	}
}
