// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SavePaymentMethodDataBankCard schema. See the pinned OpenAPI specification.
 */
public class SavePaymentMethodDataBankCard extends JsonModel {
	public SavePaymentMethodDataBankCard() {
		super();
	}

	public SavePaymentMethodDataBankCard(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_BANK_CARD = "bank_card";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code holder}; optional. Absent values return null.
	 */
	public Recipient getHolder() {
		return read("holder", Recipient.class);
	}

	/**
	 * Sets {@code holder}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setHolder(Recipient value) {
		put("holder", value);
		return this;
	}

	/**
	 * API field {@code client_ip}; optional. Absent values return null.
	 */
	public String getClientIp() {
		return read("client_ip", String.class);
	}

	/**
	 * Sets {@code client_ip}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setClientIp(String value) {
		put("client_ip", value);
		return this;
	}

	/**
	 * API field {@code confirmation}; optional. Absent values return null.
	 */
	public JsonModel getConfirmation() {
		return read("confirmation", JsonModel.class);
	}

	/**
	 * Sets {@code confirmation}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setConfirmation(JsonModel value) {
		put("confirmation", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code card}; optional. Absent values return null.
	 */
	public CardRequestDataWithCsc getCard() {
		return read("card", CardRequestDataWithCsc.class);
	}

	/**
	 * Sets {@code card}; null removes the field.
	 */
	public SavePaymentMethodDataBankCard setCard(CardRequestDataWithCsc value) {
		put("card", value);
		return this;
	}
}
