// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SbpPayoutRecipientPersonalDataRequest schema. See the pinned OpenAPI specification.
 */
public class SbpPayoutRecipientPersonalDataRequest extends JsonModel {
	public SbpPayoutRecipientPersonalDataRequest() {
		super();
	}

	public SbpPayoutRecipientPersonalDataRequest(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYOUT_STATEMENT_RECIPIENT = "payout_statement_recipient";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP_PAYOUT_RECIPIENT = "sbp_payout_recipient";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SbpPayoutRecipientPersonalDataRequest setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SbpPayoutRecipientPersonalDataRequest setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code last_name}; required. Absent values return null.
	 */
	public String getLastName() {
		return read("last_name", String.class);
	}

	/**
	 * Sets {@code last_name}; null removes the field.
	 */
	public SbpPayoutRecipientPersonalDataRequest setLastName(String value) {
		put("last_name", value);
		return this;
	}

	/**
	 * API field {@code first_name}; required. Absent values return null.
	 */
	public String getFirstName() {
		return read("first_name", String.class);
	}

	/**
	 * Sets {@code first_name}; null removes the field.
	 */
	public SbpPayoutRecipientPersonalDataRequest setFirstName(String value) {
		put("first_name", value);
		return this;
	}

	/**
	 * API field {@code middle_name}; optional. Absent values return null.
	 */
	public String getMiddleName() {
		return read("middle_name", String.class);
	}

	/**
	 * Sets {@code middle_name}; null removes the field.
	 */
	public SbpPayoutRecipientPersonalDataRequest setMiddleName(String value) {
		put("middle_name", value);
		return this;
	}
}
