// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SbpPayerBankDetails schema. See the pinned OpenAPI specification.
 */
public class SbpPayerBankDetails extends JsonModel {
	public SbpPayerBankDetails() {
		super();
	}

	public SbpPayerBankDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code bank_id}; required. Absent values return null.
	 */
	public String getBankId() {
		return read("bank_id", String.class);
	}

	/**
	 * Sets {@code bank_id}; null removes the field.
	 */
	public SbpPayerBankDetails setBankId(String value) {
		put("bank_id", value);
		return this;
	}

	/**
	 * API field {@code bic}; required. Absent values return null.
	 */
	public String getBic() {
		return read("bic", String.class);
	}

	/**
	 * Sets {@code bic}; null removes the field.
	 */
	public SbpPayerBankDetails setBic(String value) {
		put("bic", value);
		return this;
	}
}
