// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SbpParticipantBank schema. See the pinned OpenAPI specification.
 */
public class SbpParticipantBank extends JsonModel {
	public SbpParticipantBank() {
		super();
	}

	public SbpParticipantBank(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code bank_id}; required. Absent values return null.
	 */
	public String getBankId() {
		return read("bank_id", String.class);
	}

	/**
	 * Sets {@code bank_id}; null removes the field.
	 */
	public SbpParticipantBank setBankId(String value) {
		put("bank_id", value);
		return this;
	}

	/**
	 * API field {@code name}; required. Absent values return null.
	 */
	public String getName() {
		return read("name", String.class);
	}

	/**
	 * Sets {@code name}; null removes the field.
	 */
	public SbpParticipantBank setName(String value) {
		put("name", value);
		return this;
	}

	/**
	 * API field {@code bic}; required. Absent values return null.
	 */
	public String getBic() {
		return read("bic", String.class);
	}

	/**
	 * Sets {@code bic}; null removes the field.
	 */
	public SbpParticipantBank setBic(String value) {
		put("bic", value);
		return this;
	}
}
