// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SbpRefundMethod schema. See the pinned OpenAPI specification.
 */
public class SbpRefundMethod extends JsonModel {
	public SbpRefundMethod() {
		super();
	}

	public SbpRefundMethod(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_SBP = "sbp";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_ELECTRONIC_CERTIFICATE = "electronic_certificate";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SbpRefundMethod setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code sbp_operation_id}; optional. Absent values return null.
	 */
	public String getSbpOperationId() {
		return read("sbp_operation_id", String.class);
	}

	/**
	 * Sets {@code sbp_operation_id}; null removes the field.
	 */
	public SbpRefundMethod setSbpOperationId(String value) {
		put("sbp_operation_id", value);
		return this;
	}
}
