// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SearchPayoutsQuery schema. See the pinned OpenAPI specification.
 */
public class SearchPayoutsQuery extends JsonModel {
	public SearchPayoutsQuery() {
		super();
	}

	public SearchPayoutsQuery(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code created_at.gte}; optional. Absent values return null.
	 */
	public String getCreatedAtGte() {
		return read("created_at.gte", String.class);
	}

	/**
	 * Sets {@code created_at.gte}; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtGte(String value) {
		put("created_at.gte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGteAsDateTime() {
		return readDateTime("created_at.gte");
	}

	/**
	 * Sets {@code created_at.gte} as an ISO-8601 date-time; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtGteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gte", value);
		return this;
	}

	/**
	 * API field {@code created_at.gt}; optional. Absent values return null.
	 */
	public String getCreatedAtGt() {
		return read("created_at.gt", String.class);
	}

	/**
	 * Sets {@code created_at.gt}; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtGt(String value) {
		put("created_at.gt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.gt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtGtAsDateTime() {
		return readDateTime("created_at.gt");
	}

	/**
	 * Sets {@code created_at.gt} as an ISO-8601 date-time; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtGtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.gt", value);
		return this;
	}

	/**
	 * API field {@code created_at.lte}; optional. Absent values return null.
	 */
	public String getCreatedAtLte() {
		return read("created_at.lte", String.class);
	}

	/**
	 * Sets {@code created_at.lte}; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtLte(String value) {
		put("created_at.lte", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lte}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLteAsDateTime() {
		return readDateTime("created_at.lte");
	}

	/**
	 * Sets {@code created_at.lte} as an ISO-8601 date-time; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtLteAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lte", value);
		return this;
	}

	/**
	 * API field {@code created_at.lt}; optional. Absent values return null.
	 */
	public String getCreatedAtLt() {
		return read("created_at.lt", String.class);
	}

	/**
	 * Sets {@code created_at.lt}; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtLt(String value) {
		put("created_at.lt", value);
		return this;
	}

	/**
	 * Parsed {@code created_at.lt}; the string accessor keeps the exact API value.
	 */
	public java.time.OffsetDateTime getCreatedAtLtAsDateTime() {
		return readDateTime("created_at.lt");
	}

	/**
	 * Sets {@code created_at.lt} as an ISO-8601 date-time; null removes the field.
	 */
	public SearchPayoutsQuery setCreatedAtLtAsDateTime(java.time.OffsetDateTime value) {
		putDateTime("created_at.lt", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public com.google.gson.JsonObject getMetadata() {
		return read("metadata", com.google.gson.JsonObject.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public SearchPayoutsQuery setMetadata(com.google.gson.JsonObject value) {
		put("metadata", value);
		return this;
	}

	/**
	 * API field {@code limit}; optional. Absent values return null.
	 */
	public Long getLimit() {
		return read("limit", Long.class);
	}

	/**
	 * Sets {@code limit}; null removes the field.
	 */
	public SearchPayoutsQuery setLimit(Long value) {
		put("limit", value);
		return this;
	}

	/**
	 * API field {@code cursor}; optional. Absent values return null.
	 */
	public String getCursor() {
		return read("cursor", String.class);
	}

	/**
	 * Sets {@code cursor}; null removes the field.
	 */
	public SearchPayoutsQuery setCursor(String value) {
		put("cursor", value);
		return this;
	}
}
