// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Settlement schema. See the pinned OpenAPI specification.
 */
public class Settlement extends JsonModel {
	public Settlement() {
		super();
	}

	public Settlement(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CASHLESS = "cashless";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PREPAYMENT = "prepayment";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_POSTPAYMENT = "postpayment";
	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_CONSIDERATION = "consideration";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public Settlement setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public Settlement setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}
}
