// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the SettlementPayoutRefund schema. See the pinned OpenAPI specification.
 */
public class SettlementPayoutRefund extends JsonModel {
	public SettlementPayoutRefund() {
		super();
	}

	public SettlementPayoutRefund(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_PAYOUT = "payout";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public SettlementPayoutRefund setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public MonetaryAmount getAmount() {
		return read("amount", MonetaryAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public SettlementPayoutRefund setAmount(MonetaryAmount value) {
		put("amount", value);
		return this;
	}
}
