// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the ThreeDSecureDetails schema. See the pinned OpenAPI specification.
 */
public class ThreeDSecureDetails extends JsonModel {
	public ThreeDSecureDetails() {
		super();
	}

	public ThreeDSecureDetails(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code applied}; required. Absent values return null.
	 */
	public Boolean getApplied() {
		return read("applied", Boolean.class);
	}

	/**
	 * Sets {@code applied}; null removes the field.
	 */
	public ThreeDSecureDetails setApplied(Boolean value) {
		put("applied", value);
		return this;
	}
}
