// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the TransferDataCapture schema. See the pinned OpenAPI specification.
 */
public class TransferDataCapture extends JsonModel {
	public TransferDataCapture() {
		super();
	}

	public TransferDataCapture(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public TransferDataCapture setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public TransferDataCaptureAmount getAmount() {
		return read("amount", TransferDataCaptureAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public TransferDataCapture setAmount(TransferDataCaptureAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code platform_fee_amount}; optional. Absent values return null.
	 */
	public TransferDataCapturePlatformFeeAmount getPlatformFeeAmount() {
		return read("platform_fee_amount", TransferDataCapturePlatformFeeAmount.class);
	}

	/**
	 * Sets {@code platform_fee_amount}; null removes the field.
	 */
	public TransferDataCapture setPlatformFeeAmount(TransferDataCapturePlatformFeeAmount value) {
		put("platform_fee_amount", value);
		return this;
	}
}
