// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the TransferData schema. See the pinned OpenAPI specification.
 */
public class TransferData extends JsonModel {
	public TransferData() {
		super();
	}

	public TransferData(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public TransferData setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public TransferDataAmount getAmount() {
		return read("amount", TransferDataAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public TransferData setAmount(TransferDataAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code platform_fee_amount}; optional. Absent values return null.
	 */
	public TransferDataPlatformFeeAmount getPlatformFeeAmount() {
		return read("platform_fee_amount", TransferDataPlatformFeeAmount.class);
	}

	/**
	 * Sets {@code platform_fee_amount}; null removes the field.
	 */
	public TransferData setPlatformFeeAmount(TransferDataPlatformFeeAmount value) {
		put("platform_fee_amount", value);
		return this;
	}
}
