// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the Transfer schema. See the pinned OpenAPI specification.
 */
public class Transfer extends JsonModel {
	public Transfer() {
		super();
	}

	public Transfer(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_PENDING = "pending";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_WAITING_FOR_CAPTURE = "waiting_for_capture";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_SUCCEEDED = "succeeded";
	/**
	 * Documented value of {@code status}. The API may return values added later.
	 */
	public static final String STATUS_CANCELED = "canceled";

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public Transfer setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public TransferAmount getAmount() {
		return read("amount", TransferAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public Transfer setAmount(TransferAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code status}; required. Absent values return null.
	 */
	public String getStatus() {
		return read("status", String.class);
	}

	/**
	 * Sets {@code status}; null removes the field.
	 */
	public Transfer setStatus(String value) {
		put("status", value);
		return this;
	}

	/**
	 * API field {@code platform_fee_amount}; optional. Absent values return null.
	 */
	public TransferPlatformFeeAmount getPlatformFeeAmount() {
		return read("platform_fee_amount", TransferPlatformFeeAmount.class);
	}

	/**
	 * Sets {@code platform_fee_amount}; null removes the field.
	 */
	public Transfer setPlatformFeeAmount(TransferPlatformFeeAmount value) {
		put("platform_fee_amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public Transfer setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public Transfer setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
