// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the TransferDataPayment schema. See the pinned OpenAPI specification.
 */
public class TransferDataPayment extends JsonModel {
	public TransferDataPayment() {
		super();
	}

	public TransferDataPayment(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * API field {@code account_id}; required. Absent values return null.
	 */
	public String getAccountId() {
		return read("account_id", String.class);
	}

	/**
	 * Sets {@code account_id}; null removes the field.
	 */
	public TransferDataPayment setAccountId(String value) {
		put("account_id", value);
		return this;
	}

	/**
	 * API field {@code amount}; required. Absent values return null.
	 */
	public TransferDataPaymentAmount getAmount() {
		return read("amount", TransferDataPaymentAmount.class);
	}

	/**
	 * Sets {@code amount}; null removes the field.
	 */
	public TransferDataPayment setAmount(TransferDataPaymentAmount value) {
		put("amount", value);
		return this;
	}

	/**
	 * API field {@code platform_fee_amount}; optional. Absent values return null.
	 */
	public TransferDataPaymentPlatformFeeAmount getPlatformFeeAmount() {
		return read("platform_fee_amount", TransferDataPaymentPlatformFeeAmount.class);
	}

	/**
	 * Sets {@code platform_fee_amount}; null removes the field.
	 */
	public TransferDataPayment setPlatformFeeAmount(TransferDataPaymentPlatformFeeAmount value) {
		put("platform_fee_amount", value);
		return this;
	}

	/**
	 * API field {@code description}; optional. Absent values return null.
	 */
	public String getDescription() {
		return read("description", String.class);
	}

	/**
	 * Sets {@code description}; null removes the field.
	 */
	public TransferDataPayment setDescription(String value) {
		put("description", value);
		return this;
	}

	/**
	 * API field {@code metadata}; optional. Absent values return null.
	 */
	public Metadata getMetadata() {
		return read("metadata", Metadata.class);
	}

	/**
	 * Sets {@code metadata}; null removes the field.
	 */
	public TransferDataPayment setMetadata(Metadata value) {
		put("metadata", value);
		return this;
	}
}
