// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa.model;

/**
 * Typed, lossless JSON view of the WebhookList schema. See the pinned OpenAPI specification.
 */
public class WebhookList extends JsonModel {
	public WebhookList() {
		super();
	}

	public WebhookList(com.google.gson.JsonObject json) {
		super(json);
	}

	/**
	 * Documented value of {@code type}. The API may return values added later.
	 */
	public static final String TYPE_LIST = "list";

	/**
	 * API field {@code type}; required. Absent values return null.
	 */
	public String getType() {
		return read("type", String.class);
	}

	/**
	 * Sets {@code type}; null removes the field.
	 */
	public WebhookList setType(String value) {
		put("type", value);
		return this;
	}

	/**
	 * API field {@code items}; required. Absent values return null.
	 */
	public java.util.List<Webhook> getItems() {
		return read("items", new com.google.gson.reflect.TypeToken<java.util.List<Webhook>>() {
		}.getType());
	}

	/**
	 * Sets {@code items}; null removes the field.
	 */
	public WebhookList setItems(java.util.List<Webhook> value) {
		put("items", value);
		return this;
	}
}
