// Generated by tools/generate_v3.py. Do not edit by hand.
package ru.deelter.yookassa;

import ru.deelter.yookassa.model.*;

import java.io.IOException;
import java.util.Objects;

/**
 * Every operation of the pinned YooKassa OpenAPI snapshot. Use these methods through {@link YooKassa}.
 * Write operations require a caller-persisted idempotence key: reuse it only to retry the same operation.
 */
public abstract class YooKassaOperations {
	YooKassaOperations() {
	}

	abstract <T> T execute(HttpMethod method, String[] path, JsonModel query, JsonModel body,
	                       String idempotenceKey, Class<T> responseType) throws IOException;

	/**
	 * Create a payment. POST /payments.
	 */
	public Payment createPayment(CreatePaymentRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"payments"}, null, body, idempotenceKey, Payment.class);
	}

	/**
	 * List payments. GET /payments.
	 */
	public PaymentList getPayments(GetPaymentsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payments"}, query, null, null, PaymentList.class);
	}

	/**
	 * Get payment information. GET /payments/{payment_id}.
	 */
	public Payment getPayment(String paymentId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payments", RequestEncoding.id(paymentId)}, null, null, null, Payment.class);
	}

	/**
	 * Capture a payment. POST /payments/{payment_id}/capture.
	 */
	public Payment capturePayment(String paymentId, PaymentCaptureRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"payments", RequestEncoding.id(paymentId), "capture"}, null, body, idempotenceKey, Payment.class);
	}

	/**
	 * Cancel a payment. POST /payments/{payment_id}/cancel.
	 */
	public Payment cancelPayment(String paymentId, String idempotenceKey) throws IOException {
		return execute(HttpMethod.POST, new String[]{"payments", RequestEncoding.id(paymentId), "cancel"}, null, null, idempotenceKey, Payment.class);
	}

	/**
	 * Create a payment method. POST /payment_methods.
	 */
	public JsonModel createPaymentMethod(JsonModel body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"payment_methods"}, null, body, idempotenceKey, JsonModel.class);
	}

	/**
	 * Get payment method information. GET /payment_methods/{payment_method_id}.
	 */
	public JsonModel getPaymentMethod(String paymentMethodId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payment_methods", RequestEncoding.id(paymentMethodId)}, null, null, null, JsonModel.class);
	}

	/**
	 * Create an invoice. POST /invoices.
	 */
	public Invoice createInvoice(CreateInvoiceRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"invoices"}, null, body, idempotenceKey, Invoice.class);
	}

	/**
	 * Get invoice information. GET /invoices/{invoice_id}.
	 */
	public Invoice getInvoice(String invoiceId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"invoices", RequestEncoding.id(invoiceId)}, null, null, null, Invoice.class);
	}

	/**
	 * Create a refund. POST /refunds.
	 */
	public Refund createRefund(RefundRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"refunds"}, null, body, idempotenceKey, Refund.class);
	}

	/**
	 * List refunds. GET /refunds.
	 */
	public RefundList getRefunds(GetRefundsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"refunds"}, query, null, null, RefundList.class);
	}

	/**
	 * Get refund information. GET /refunds/{refund_id}.
	 */
	public Refund getRefund(String refundId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"refunds", RequestEncoding.id(refundId)}, null, null, null, Refund.class);
	}

	/**
	 * Create a receipt. POST /receipts.
	 */
	public Receipt createReceipt(PostReceiptData body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"receipts"}, null, body, idempotenceKey, Receipt.class);
	}

	/**
	 * List receipts. GET /receipts.
	 */
	public GetReceiptsResponse getReceipts(GetReceiptsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"receipts"}, query, null, null, GetReceiptsResponse.class);
	}

	/**
	 * Get receipt information. GET /receipts/{receipt_id}.
	 */
	public Receipt getReceipt(String receiptId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"receipts", RequestEncoding.id(receiptId)}, null, null, null, Receipt.class);
	}

	/**
	 * Create a deal. POST /deals.
	 */
	public SafeDeal createDeal(SafeDealRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"deals"}, null, body, idempotenceKey, SafeDeal.class);
	}

	/**
	 * List deals. GET /deals.
	 */
	public GetDealsResponse getDeals(GetDealsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"deals"}, query, null, null, GetDealsResponse.class);
	}

	/**
	 * Get deal information. GET /deals/{deal_id}.
	 */
	public SafeDeal getDeal(String dealId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"deals", RequestEncoding.id(dealId)}, null, null, null, SafeDeal.class);
	}

	/**
	 * Create a payout. POST /payouts.
	 */
	public Payout createPayout(PayoutRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"payouts"}, null, body, idempotenceKey, Payout.class);
	}

	/**
	 * List payouts. GET /payouts.
	 */
	public PayoutsList getPayouts(GetPayoutsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payouts"}, query, null, null, PayoutsList.class);
	}

	/**
	 * Search for payouts. GET /payouts/search.
	 */
	public PayoutsList searchPayouts(SearchPayoutsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payouts", "search"}, query, null, null, PayoutsList.class);
	}

	/**
	 * Get payout information. GET /payouts/{payout_id}.
	 */
	public Payout getPayout(String payoutId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"payouts", RequestEncoding.id(payoutId)}, null, null, null, Payout.class);
	}

	/**
	 * List FPS participants. GET /sbp_banks.
	 */
	public GetSbpBanksResponse getSbpBanks() throws IOException {
		return execute(HttpMethod.GET, new String[]{"sbp_banks"}, null, null, null, GetSbpBanksResponse.class);
	}

	/**
	 * Create personal data. POST /personal_data.
	 */
	public PersonalData createPersonalData(JsonModel body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"personal_data"}, null, body, idempotenceKey, PersonalData.class);
	}

	/**
	 * Get information on personal data. GET /personal_data/{personal_data_id}.
	 */
	public PersonalData getPersonalData(String personalDataId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"personal_data", RequestEncoding.id(personalDataId)}, null, null, null, PersonalData.class);
	}

	/**
	 * Create a webhook. POST /webhooks.
	 */
	public Webhook createWebhook(CreateWebhookRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"webhooks"}, null, body, idempotenceKey, Webhook.class);
	}

	/**
	 * List created webhooks. GET /webhooks.
	 */
	public WebhookList getWebhooks() throws IOException {
		return execute(HttpMethod.GET, new String[]{"webhooks"}, null, null, null, WebhookList.class);
	}

	/**
	 * Delete webhook. DELETE /webhooks/{webhook_id}.
	 */
	public void deleteWebhook(String webhookId, String idempotenceKey) throws IOException {
		execute(HttpMethod.DELETE, new String[]{"webhooks", RequestEncoding.id(webhookId)}, null, null, idempotenceKey, null);
	}

	/**
	 * Get information about the settings of a store or gateway. GET /me.
	 */
	public Me getSettings(GetSettingsQuery query) throws IOException {
		return execute(HttpMethod.GET, new String[]{"me"}, query, null, null, Me.class);
	}

	/**
	 * Activate a POS link. POST /pos_links.
	 */
	public PosLinkInfo createPosLink(CreatePosLinkRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"pos_links"}, null, body, idempotenceKey, PosLinkInfo.class);
	}

	/**
	 * Change the trading location linked to a POS link. POST /pos_links/{pos_link_id}/recipient.
	 */
	public PosLinkInfo changePosLinkRecipient(String posLinkId, RecipientPosLinkRequest body, String idempotenceKey) throws IOException {
		Objects.requireNonNull(body, "body");
		return execute(HttpMethod.POST, new String[]{"pos_links", RequestEncoding.id(posLinkId), "recipient"}, null, body, idempotenceKey, PosLinkInfo.class);
	}

	/**
	 * Deactivate a POS link. POST /pos_links/{pos_link_id}/deactivate.
	 */
	public PosLinkInfo deactivatePosLink(String posLinkId, String idempotenceKey) throws IOException {
		return execute(HttpMethod.POST, new String[]{"pos_links", RequestEncoding.id(posLinkId), "deactivate"}, null, null, idempotenceKey, PosLinkInfo.class);
	}

	/**
	 * Activate a previously deactivated POS link. POST /pos_links/{pos_link_id}/activate.
	 */
	public PosLinkInfo activatePosLink(String posLinkId, String idempotenceKey) throws IOException {
		return execute(HttpMethod.POST, new String[]{"pos_links", RequestEncoding.id(posLinkId), "activate"}, null, null, idempotenceKey, PosLinkInfo.class);
	}

	/**
	 * Get POS link information. GET /pos_links/{pos_link_id}.
	 */
	public PosLinkInfo getPosLink(String posLinkId) throws IOException {
		return execute(HttpMethod.GET, new String[]{"pos_links", RequestEncoding.id(posLinkId)}, null, null, null, PosLinkInfo.class);
	}
}
